/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  GetTaskDisposalByIdParams,
  IdRequest,
  ResultBoolean,
  ResultPageTaskDisposal,
  ResultString,
  ResultTaskDisposal,
  TaskDisposalAddRequest,
  TaskDisposalQueryRequest,
  TaskDisposalUpdateRequest
} from '../../models';

import { mutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const updateTaskDisposal = (
    taskDisposalUpdateRequest: TaskDisposalUpdateRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/task/disposal/update`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: taskDisposalUpdateRequest
    },
      options);
    }
  export const listTaskDisposalsByPage = (
    taskDisposalQueryRequest: TaskDisposalQueryRequest,
 options?: SecondParameter<typeof mutator<ResultPageTaskDisposal>>,) => {
      return mutator<ResultPageTaskDisposal>(
      {url: `/api/task/disposal/list/page`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: taskDisposalQueryRequest
    },
      options);
    }
  export const deleteTaskDisposal = (
    idRequest: IdRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/task/disposal/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: idRequest
    },
      options);
    }
  export const addTaskDisposal = (
    taskDisposalAddRequest: TaskDisposalAddRequest,
 options?: SecondParameter<typeof mutator<ResultString>>,) => {
      return mutator<ResultString>(
      {url: `/api/task/disposal/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: taskDisposalAddRequest
    },
      options);
    }
  export const getTaskDisposalById = (
    params: GetTaskDisposalByIdParams,
 options?: SecondParameter<typeof mutator<ResultTaskDisposal>>,) => {
      return mutator<ResultTaskDisposal>(
      {url: `/api/task/disposal/get`, method: 'GET',
        params
    },
      options);
    }

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type UpdateTaskDisposalResult = NonNullable<Awaited<ReturnType<typeof updateTaskDisposal>>>
export type ListTaskDisposalsByPageResult = NonNullable<Awaited<ReturnType<typeof listTaskDisposalsByPage>>>
export type DeleteTaskDisposalResult = NonNullable<Awaited<ReturnType<typeof deleteTaskDisposal>>>
export type AddTaskDisposalResult = NonNullable<Awaited<ReturnType<typeof addTaskDisposal>>>
export type GetTaskDisposalByIdResult = NonNullable<Awaited<ReturnType<typeof getTaskDisposalById>>>
