/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  AiChatMessagesQueryRequest,
  AiChatRequest,
  AiChatSessionQueryRequest,
  GetSessionByIdParams,
  IdRequest,
  ResultAiChatSessionSummary,
  ResultListAiChatMessage,
  ResultPageAiChatSessionSummary,
  ResultVoid,
  ServerSentEventString
} from '../../models';

import { mutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const listMessages = (
    aiChatMessagesQueryRequest: AiChatMessagesQueryRequest,
 options?: SecondParameter<typeof mutator<ResultListAiChatMessage>>,) => {
      return mutator<ResultListAiChatMessage>(
      {url: `/api/ai/sessions/messages/list`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aiChatMessagesQueryRequest
    },
      options);
    }
  export const listSessions = (
    aiChatSessionQueryRequest: AiChatSessionQueryRequest,
 options?: SecondParameter<typeof mutator<ResultPageAiChatSessionSummary>>,) => {
      return mutator<ResultPageAiChatSessionSummary>(
      {url: `/api/ai/sessions/list/page`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aiChatSessionQueryRequest
    },
      options);
    }
  export const deleteSession = (
    idRequest: IdRequest,
 options?: SecondParameter<typeof mutator<ResultVoid>>,) => {
      return mutator<ResultVoid>(
      {url: `/api/ai/sessions/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: idRequest
    },
      options);
    }
  export const chatStream = (
    aiChatRequest: AiChatRequest,
 options?: SecondParameter<typeof mutator<ServerSentEventString[]>>,) => {
      return mutator<ServerSentEventString[]>(
      {url: `/api/ai/chat`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aiChatRequest
    },
      options);
    }
  export const getSessionById = (
    params: GetSessionByIdParams,
 options?: SecondParameter<typeof mutator<ResultAiChatSessionSummary>>,) => {
      return mutator<ResultAiChatSessionSummary>(
      {url: `/api/ai/sessions/get`, method: 'GET',
        params
    },
      options);
    }

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type ListMessagesResult = NonNullable<Awaited<ReturnType<typeof listMessages>>>
export type ListSessionsResult = NonNullable<Awaited<ReturnType<typeof listSessions>>>
export type DeleteSessionResult = NonNullable<Awaited<ReturnType<typeof deleteSession>>>
export type ChatStreamResult = NonNullable<Awaited<ReturnType<typeof chatStream>>>
export type GetSessionByIdResult = NonNullable<Awaited<ReturnType<typeof getSessionById>>>
