/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  GetTicketByIdParams,
  IdRequest,
  ResultBoolean,
  ResultPageTicket,
  ResultString,
  ResultTicket,
  TicketAddRequest,
  TicketQueryRequest,
  TicketUpdateRequest
} from '../../models';

import { mutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const updateTicket = (
    ticketUpdateRequest: TicketUpdateRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/ticket/update`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: ticketUpdateRequest
    },
      options);
    }
  export const listTicketsByPage = (
    ticketQueryRequest: TicketQueryRequest,
 options?: SecondParameter<typeof mutator<ResultPageTicket>>,) => {
      return mutator<ResultPageTicket>(
      {url: `/api/ticket/list/page`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: ticketQueryRequest
    },
      options);
    }
  export const deleteTicket = (
    idRequest: IdRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/ticket/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: idRequest
    },
      options);
    }
  export const addTicket = (
    ticketAddRequest: TicketAddRequest,
 options?: SecondParameter<typeof mutator<ResultString>>,) => {
      return mutator<ResultString>(
      {url: `/api/ticket/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: ticketAddRequest
    },
      options);
    }
  export const getTicketById = (
    params: GetTicketByIdParams,
 options?: SecondParameter<typeof mutator<ResultTicket>>,) => {
      return mutator<ResultTicket>(
      {url: `/api/ticket/get`, method: 'GET',
        params
    },
      options);
    }

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type UpdateTicketResult = NonNullable<Awaited<ReturnType<typeof updateTicket>>>
export type ListTicketsByPageResult = NonNullable<Awaited<ReturnType<typeof listTicketsByPage>>>
export type DeleteTicketResult = NonNullable<Awaited<ReturnType<typeof deleteTicket>>>
export type AddTicketResult = NonNullable<Awaited<ReturnType<typeof addTicket>>>
export type GetTicketByIdResult = NonNullable<Awaited<ReturnType<typeof getTicketById>>>
