/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  AttractionsAddRequest,
  AttractionsQueryRequest,
  AttractionsUpdateRequest,
  GetAttractionsByIdParams,
  IdRequest,
  ResultAttractions,
  ResultBoolean,
  ResultPageAttractions,
  ResultString
} from '../../models';

import { mutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const updateAttractions = (
    attractionsUpdateRequest: AttractionsUpdateRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/attractions/update`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: attractionsUpdateRequest
    },
      options);
    }
  export const listAttractionsByPage = (
    attractionsQueryRequest: AttractionsQueryRequest,
 options?: SecondParameter<typeof mutator<ResultPageAttractions>>,) => {
      return mutator<ResultPageAttractions>(
      {url: `/api/attractions/list/page`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: attractionsQueryRequest
    },
      options);
    }
  export const deleteAttractions = (
    idRequest: IdRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/attractions/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: idRequest
    },
      options);
    }
  export const addAttractions = (
    attractionsAddRequest: AttractionsAddRequest,
 options?: SecondParameter<typeof mutator<ResultString>>,) => {
      return mutator<ResultString>(
      {url: `/api/attractions/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: attractionsAddRequest
    },
      options);
    }
  export const getAttractionsById = (
    params: GetAttractionsByIdParams,
 options?: SecondParameter<typeof mutator<ResultAttractions>>,) => {
      return mutator<ResultAttractions>(
      {url: `/api/attractions/get`, method: 'GET',
        params
    },
      options);
    }

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type UpdateAttractionsResult = NonNullable<Awaited<ReturnType<typeof updateAttractions>>>
export type ListAttractionsByPageResult = NonNullable<Awaited<ReturnType<typeof listAttractionsByPage>>>
export type DeleteAttractionsResult = NonNullable<Awaited<ReturnType<typeof deleteAttractions>>>
export type AddAttractionsResult = NonNullable<Awaited<ReturnType<typeof addAttractions>>>
export type GetAttractionsByIdResult = NonNullable<Awaited<ReturnType<typeof getAttractionsById>>>
