/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  AttractionsTypeAddRequest,
  AttractionsTypeUpdateRequest,
  IdRequest,
  ResultBoolean,
  ResultListAttractionsType,
  ResultString
} from '../../models';

import { mutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const updateType = (
    attractionsTypeUpdateRequest: AttractionsTypeUpdateRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/attractions/type/update`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: attractionsTypeUpdateRequest
    },
      options);
    }
  export const deleteType = (
    idRequest: IdRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/attractions/type/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: idRequest
    },
      options);
    }
  export const addType = (
    attractionsTypeAddRequest: AttractionsTypeAddRequest,
 options?: SecondParameter<typeof mutator<ResultString>>,) => {
      return mutator<ResultString>(
      {url: `/api/attractions/type/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: attractionsTypeAddRequest
    },
      options);
    }
  export const listAllTypes = (

 options?: SecondParameter<typeof mutator<ResultListAttractionsType>>,) => {
      return mutator<ResultListAttractionsType>(
      {url: `/api/attractions/type/list/all`, method: 'GET'
    },
      options);
    }

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type UpdateTypeResult = NonNullable<Awaited<ReturnType<typeof updateType>>>
export type DeleteTypeResult = NonNullable<Awaited<ReturnType<typeof deleteType>>>
export type AddTypeResult = NonNullable<Awaited<ReturnType<typeof addType>>>
export type ListAllTypesResult = NonNullable<Awaited<ReturnType<typeof listAllTypes>>>
