/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  GetUserByIdParams,
  IdRequest,
  ResultBoolean,
  ResultLoginUser,
  ResultPageUser,
  ResultString,
  ResultUser,
  UserAddRequest,
  UserLoginRequest,
  UserQueryRequest,
  UserRegisterRequest,
  UserResetPasswordRequest,
  UserUpdateMyRequest,
  UserUpdateRequest
} from '../../models';

import { mutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const updateUser = (
    userUpdateRequest: UserUpdateRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/user/update`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userUpdateRequest
    },
      options);
    }
  export const updateMyUser = (
    userUpdateMyRequest: UserUpdateMyRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/user/update/my`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userUpdateMyRequest
    },
      options);
    }
  export const resetPassword = (
    userResetPasswordRequest: UserResetPasswordRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/user/reset/password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userResetPasswordRequest
    },
      options);
    }
  export const userRegister = (
    userRegisterRequest: UserRegisterRequest,
 options?: SecondParameter<typeof mutator<ResultString>>,) => {
      return mutator<ResultString>(
      {url: `/api/user/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userRegisterRequest
    },
      options);
    }
  export const logout = (

 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/user/logout`, method: 'POST'
    },
      options);
    }
  export const userLogin = (
    userLoginRequest: UserLoginRequest,
 options?: SecondParameter<typeof mutator<ResultLoginUser>>,) => {
      return mutator<ResultLoginUser>(
      {url: `/api/user/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userLoginRequest
    },
      options);
    }
  export const listUserByPage = (
    userQueryRequest: UserQueryRequest,
 options?: SecondParameter<typeof mutator<ResultPageUser>>,) => {
      return mutator<ResultPageUser>(
      {url: `/api/user/list/page`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userQueryRequest
    },
      options);
    }
  export const deleteUser = (
    idRequest: IdRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/user/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: idRequest
    },
      options);
    }
  export const addUser = (
    userAddRequest: UserAddRequest,
 options?: SecondParameter<typeof mutator<ResultString>>,) => {
      return mutator<ResultString>(
      {url: `/api/user/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userAddRequest
    },
      options);
    }
  export const getUserById = (
    params: GetUserByIdParams,
 options?: SecondParameter<typeof mutator<ResultUser>>,) => {
      return mutator<ResultUser>(
      {url: `/api/user/get`, method: 'GET',
        params
    },
      options);
    }
  export const getLoginUser = (

 options?: SecondParameter<typeof mutator<ResultLoginUser>>,) => {
      return mutator<ResultLoginUser>(
      {url: `/api/user/get/login`, method: 'GET'
    },
      options);
    }

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type UpdateUserResult = NonNullable<Awaited<ReturnType<typeof updateUser>>>
export type UpdateMyUserResult = NonNullable<Awaited<ReturnType<typeof updateMyUser>>>
export type ResetPasswordResult = NonNullable<Awaited<ReturnType<typeof resetPassword>>>
export type UserRegisterResult = NonNullable<Awaited<ReturnType<typeof userRegister>>>
export type LogoutResult = NonNullable<Awaited<ReturnType<typeof logout>>>
export type UserLoginResult = NonNullable<Awaited<ReturnType<typeof userLogin>>>
export type ListUserByPageResult = NonNullable<Awaited<ReturnType<typeof listUserByPage>>>
export type DeleteUserResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>
export type AddUserResult = NonNullable<Awaited<ReturnType<typeof addUser>>>
export type GetUserByIdResult = NonNullable<Awaited<ReturnType<typeof getUserById>>>
export type GetLoginUserResult = NonNullable<Awaited<ReturnType<typeof getLoginUser>>>
