/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  IdRequest,
  ResultBoolean,
  ResultPageTaskCheckin,
  ResultString,
  TaskCheckinAddRequest,
  TaskCheckinQueryRequest
} from '../../models';

import { mutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const listTaskCheckinsByPage = (
    taskCheckinQueryRequest: TaskCheckinQueryRequest,
 options?: SecondParameter<typeof mutator<ResultPageTaskCheckin>>,) => {
      return mutator<ResultPageTaskCheckin>(
      {url: `/api/task/checkin/list/page`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: taskCheckinQueryRequest
    },
      options);
    }
  export const deleteTaskCheckin = (
    idRequest: IdRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/task/checkin/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: idRequest
    },
      options);
    }
  export const addTaskCheckin = (
    taskCheckinAddRequest: TaskCheckinAddRequest,
 options?: SecondParameter<typeof mutator<ResultString>>,) => {
      return mutator<ResultString>(
      {url: `/api/task/checkin/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: taskCheckinAddRequest
    },
      options);
    }

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type ListTaskCheckinsByPageResult = NonNullable<Awaited<ReturnType<typeof listTaskCheckinsByPage>>>
export type DeleteTaskCheckinResult = NonNullable<Awaited<ReturnType<typeof deleteTaskCheckin>>>
export type AddTaskCheckinResult = NonNullable<Awaited<ReturnType<typeof addTaskCheckin>>>
