/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  ResultBoolean,
  ResultUserNotificationSettingVO,
  UserNotificationSettingUpdateRequest
} from '../../models';

import { mutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const updateMySettings = (
    userNotificationSettingUpdateRequest: UserNotificationSettingUpdateRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/user/setting/my/update`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userNotificationSettingUpdateRequest
    },
      options);
    }
  export const getMySettings = (

 options?: SecondParameter<typeof mutator<ResultUserNotificationSettingVO>>,) => {
      return mutator<ResultUserNotificationSettingVO>(
      {url: `/api/user/setting/my`, method: 'GET'
    },
      options);
    }

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type UpdateMySettingsResult = NonNullable<Awaited<ReturnType<typeof updateMySettings>>>
export type GetMySettingsResult = NonNullable<Awaited<ReturnType<typeof getMySettings>>>
