/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  CodeSendRequest,
  ResultVoid
} from '../../models';

import { mutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const send = (
    codeSendRequest: CodeSendRequest,
 options?: SecondParameter<typeof mutator<ResultVoid>>,) => {
      return mutator<ResultVoid>(
      {url: `/api/code/send`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: codeSendRequest
    },
      options);
    }

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type SendResult = NonNullable<Awaited<ReturnType<typeof send>>>
