/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  GetDisastersByIdParams,
  IdRequest,
  NaturalDisastersAddRequest,
  NaturalDisastersQueryRequest,
  NaturalDisastersUpdateRequest,
  ResultBoolean,
  ResultNaturalDisasters,
  ResultPageNaturalDisasters,
  ResultString
} from '../../models';

import { mutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const updateDisasters = (
    naturalDisastersUpdateRequest: NaturalDisastersUpdateRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/natural/disasters/update`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: naturalDisastersUpdateRequest
    },
      options);
    }
  export const listDisastersByPage = (
    naturalDisastersQueryRequest: NaturalDisastersQueryRequest,
 options?: SecondParameter<typeof mutator<ResultPageNaturalDisasters>>,) => {
      return mutator<ResultPageNaturalDisasters>(
      {url: `/api/natural/disasters/list/page`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: naturalDisastersQueryRequest
    },
      options);
    }
  export const deleteDisasters = (
    idRequest: IdRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/natural/disasters/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: idRequest
    },
      options);
    }
  export const addDisasters = (
    naturalDisastersAddRequest: NaturalDisastersAddRequest,
 options?: SecondParameter<typeof mutator<ResultString>>,) => {
      return mutator<ResultString>(
      {url: `/api/natural/disasters/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: naturalDisastersAddRequest
    },
      options);
    }
  export const getDisastersById = (
    params: GetDisastersByIdParams,
 options?: SecondParameter<typeof mutator<ResultNaturalDisasters>>,) => {
      return mutator<ResultNaturalDisasters>(
      {url: `/api/natural/disasters/get`, method: 'GET',
        params
    },
      options);
    }

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type UpdateDisastersResult = NonNullable<Awaited<ReturnType<typeof updateDisasters>>>
export type ListDisastersByPageResult = NonNullable<Awaited<ReturnType<typeof listDisastersByPage>>>
export type DeleteDisastersResult = NonNullable<Awaited<ReturnType<typeof deleteDisasters>>>
export type AddDisastersResult = NonNullable<Awaited<ReturnType<typeof addDisasters>>>
export type GetDisastersByIdResult = NonNullable<Awaited<ReturnType<typeof getDisastersById>>>
