/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  GetOrderByIdParams,
  IdRequest,
  OrderAddRequest,
  OrderQueryRequest,
  OrderUpdateRequest,
  ResultBoolean,
  ResultOrder,
  ResultPageOrder,
  ResultString
} from '../../models';

import { mutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const updateOrder = (
    orderUpdateRequest: OrderUpdateRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/order/update`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: orderUpdateRequest
    },
      options);
    }
  export const listOrdersByPage = (
    orderQueryRequest: OrderQueryRequest,
 options?: SecondParameter<typeof mutator<ResultPageOrder>>,) => {
      return mutator<ResultPageOrder>(
      {url: `/api/order/list/page`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: orderQueryRequest
    },
      options);
    }
  export const deleteOrder = (
    idRequest: IdRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/order/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: idRequest
    },
      options);
    }
  export const cancelOrder = (
    idRequest: IdRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/order/cancel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: idRequest
    },
      options);
    }
  export const addOrder = (
    orderAddRequest: OrderAddRequest,
 options?: SecondParameter<typeof mutator<ResultString>>,) => {
      return mutator<ResultString>(
      {url: `/api/order/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: orderAddRequest
    },
      options);
    }
  export const getOrderById = (
    params: GetOrderByIdParams,
 options?: SecondParameter<typeof mutator<ResultOrder>>,) => {
      return mutator<ResultOrder>(
      {url: `/api/order/get`, method: 'GET',
        params
    },
      options);
    }

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type UpdateOrderResult = NonNullable<Awaited<ReturnType<typeof updateOrder>>>
export type ListOrdersByPageResult = NonNullable<Awaited<ReturnType<typeof listOrdersByPage>>>
export type DeleteOrderResult = NonNullable<Awaited<ReturnType<typeof deleteOrder>>>
export type CancelOrderResult = NonNullable<Awaited<ReturnType<typeof cancelOrder>>>
export type AddOrderResult = NonNullable<Awaited<ReturnType<typeof addOrder>>>
export type GetOrderByIdResult = NonNullable<Awaited<ReturnType<typeof getOrderById>>>
