/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  ResultString,
  UploadFileBody,
  UploadFileParams
} from '../../models';

import { mutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * 支持图片及附件。biz字段限传：avatar/inspection/disposal/publicize/route/attraction
 * @summary 上传文件
 */
export const uploadFile = (
    uploadFileBody: UploadFileBody,
    params: UploadFileParams,
 options?: SecondParameter<typeof mutator<ResultString>>,) => {const formData = new FormData();
formData.append(`file`, uploadFileBody.file);

      return mutator<ResultString>(
      {url: `/api/file/upload`, method: 'POST',
       data: formData,
        params
    },
      options);
    }

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type UploadFileResult = NonNullable<Awaited<ReturnType<typeof uploadFile>>>
