/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface AiChatSessionSummary {
  /** 会话 ID（与发消息时的 sessionId 一致） */
  sessionId?: string;
  /** 标题摘要 */
  title?: string;
  /** 最近更新时间 */
  updateTime?: string;
}
