/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AiChatMessageRole } from './aiChatMessageRole';

export interface AiChatMessage {
  /** 消息 id */
  id?: string;
  /** 角色：USER / ASSISTANT */
  role?: AiChatMessageRole;
  /** 正文 */
  content?: string;
  /** 创建时间 */
  createTime?: string;
}
