/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface AiChatRequest {
  /**
     * 消息内容
     * @minLength 0
     * @maxLength 2000
     */
  message: string;
  /** 会话 id（与 LangChain memoryId、历史一致）。续聊必填；首轮不传则从响应头 X-Ai-Session-Id 取服务端分配的 id */
  sessionId?: string;
}
