/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface AiChatMessagesQueryRequest {
  /**
     * 会话 id
     * @minLength 1
     */
  sessionId: string;
}
