/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AiChatSessionQueryRequestSortOrder } from './aiChatSessionQueryRequestSortOrder';

export interface AiChatSessionQueryRequest {
  /**
     * 页码
     * @minimum 1
     */
  current?: number;
  /**
     * 分页大小
     * @minimum 1
     * @maximum 100
     */
  pageSize?: number;
  /** 排序字段 */
  sortField?: string;
  /** 排序方向 */
  sortOrder?: AiChatSessionQueryRequestSortOrder;
  /** 搜索关键词 */
  search?: string;
  /** 按标题关键词筛选（可选） */
  titleKeyword?: string;
}
