/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 角色：USER / ASSISTANT
 */
export type AiChatMessageRole = typeof AiChatMessageRole[keyof typeof AiChatMessageRole];


export const AiChatMessageRole = {
  USER: 'USER',
  ASSISTANT: 'ASSISTANT',
} as const;
