/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AttractionsRouteItem } from './attractionsRouteItem';

export interface AttractionsRoute {
  /** ID */
  id?: string;
  /** 创建时间 */
  createTime?: string;
  /** 更新时间 */
  updateTime?: string;
  /** 路线名称 */
  routeName?: string;
  /** 详细描述 */
  routeDescription?: string;
  /** 图片 */
  routeImage?: string;
  /** 视频 */
  routeVideo?: string;
  /** 游玩时长(分钟) */
  estimatedDurationMinutes?: number;
  /** 路线项 */
  routeItems?: AttractionsRouteItem[];
}
