/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Attractions } from './attractions';

export interface AttractionsRouteItem {
  /** ID */
  id?: string;
  /** 创建时间 */
  createTime?: string;
  /** 更新时间 */
  updateTime?: string;
  /** 路线 ID */
  routeId?: string;
  /** 景点 ID */
  attractionsId?: string;
  /** 排序 */
  sortOrder?: number;
  /** 停靠备注 */
  stopNote?: string;
  /** 停留时长(分钟) */
  estimatedStayMinutes?: number;
  /** 景点详情 */
  attractions?: Attractions;
}
