/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AttractionsType } from './attractionsType';
import type { User } from './user';

export interface Attractions {
  /** ID */
  id?: string;
  /** 创建时间 */
  createTime?: string;
  /** 更新时间 */
  updateTime?: string;
  /** 景点名称 */
  attractionsName?: string;
  /** 经度 */
  attractionsLng?: number;
  /** 纬度 */
  attractionsLat?: number;
  /** 景点图片 */
  attractionsImage?: string;
  /** 景点视频 */
  attractionsVideo?: string;
  /** 景点描述 */
  attractionsDescription?: string;
  /** 巡查员信息 */
  inspector?: User;
  /** 添加者信息 */
  user?: User;
  /** 关联类型列表 */
  types?: AttractionsType[];
}
