/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface AttractionsTypeUpdateRequest {
  /**
     * ID
     * @minLength 1
     */
  id: string;
  /**
     * 类型名称
     * @minLength 0
     * @maxLength 50
     */
  typeName?: string;
  /**
     * 类型描述
     * @minLength 0
     * @maxLength 512
     */
  typeDescription?: string;
}
