/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface AttractionsAddRequest {
  /**
     * 景点名称
     * @minLength 0
     * @maxLength 50
     */
  attractionsName: string;
  /**
     * 经度
     * @minimum -180
     * @maximum 180
     */
  attractionsLng: number;
  /**
     * 纬度
     * @minimum -90
     * @maximum 90
     */
  attractionsLat: number;
  /**
     * 景点图片
     * @minLength 0
     * @maxLength 1024
     */
  attractionsImage?: string;
  /**
     * 景点视频
     * @minLength 0
     * @maxLength 1024
     */
  attractionsVideo?: string;
  /**
     * 景点描述
     * @minLength 0
     * @maxLength 2000
     */
  attractionsDescription?: string;
  /** 巡查员 ID */
  inspectorId?: string;
  /** 关联类型 ID 列表 */
  typeIds?: string[];
}
