/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AttractionsQueryRequestSortOrder } from './attractionsQueryRequestSortOrder';

export interface AttractionsQueryRequest {
  /**
     * 页码
     * @minimum 1
     */
  current?: number;
  /**
     * 分页大小
     * @minimum 1
     * @maximum 100
     */
  pageSize?: number;
  /** 排序字段 */
  sortField?: string;
  /** 排序方向 */
  sortOrder?: AttractionsQueryRequestSortOrder;
  /** 搜索关键词 */
  search?: string;
  /** 景点 ID */
  id?: string;
  /** 景点名称 (模糊查询) */
  attractionsName?: string;
  /** 景点描述 (模糊查询) */
  attractionsDescription?: string;
  /** 绑定的巡查员 ID */
  inspectorId?: string;
  /** 关联的类型 ID 列表 */
  attractionsTypeIds?: string[];
}
