/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RouteItemUpdateRequest } from './routeItemUpdateRequest';

export interface AttractionsRouteUpdateRequest {
  /**
     * ID
     * @minLength 1
     */
  id: string;
  /**
     * 路线名称
     * @minLength 0
     * @maxLength 100
     */
  routeName?: string;
  /**
     * 路线描述
     * @minLength 0
     * @maxLength 2000
     */
  routeDescription?: string;
  /**
     * 路线图片 URL
     * @minLength 0
     * @maxLength 1024
     */
  routeImage?: string;
  /**
     * 路线视频 URL
     * @minLength 0
     * @maxLength 1024
     */
  routeVideo?: string;
  /** 预计游玩时长 (分钟) */
  estimatedDurationMinutes?: number;
  /** 更新后的景点项列表 */
  routeItems?: RouteItemUpdateRequest[];
}
