/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AttractionsRouteQueryRequestSortOrder } from './attractionsRouteQueryRequestSortOrder';

export interface AttractionsRouteQueryRequest {
  /**
     * 页码
     * @minimum 1
     */
  current?: number;
  /**
     * 分页大小
     * @minimum 1
     * @maximum 100
     */
  pageSize?: number;
  /** 排序字段 */
  sortField?: string;
  /** 排序方向 */
  sortOrder?: AttractionsRouteQueryRequestSortOrder;
  /** 搜索关键词 */
  search?: string;
  /** 路线 ID */
  id?: string;
  /** 路线名称 (模糊查询) */
  routeName?: string;
  /** 路线描述 (模糊查询) */
  routeDescription?: string;
}
