/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 排序方向
 */
export type AttractionsRouteQueryRequestSortOrder = typeof AttractionsRouteQueryRequestSortOrder[keyof typeof AttractionsRouteQueryRequestSortOrder];


export const AttractionsRouteQueryRequestSortOrder = {
  ascend: 'ascend',
  descend: 'descend',
} as const;
