/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CodeSendRequest {
  /**
     * 接收验证码的邮箱地址
     * @minLength 0
     * @maxLength 64
     */
  email: string;
  /**
     * 发送场景：register(注册)/reset(重置)/update_email(更换邮箱)/update_sensitive(更改敏感信息)
     * @minLength 0
     * @maxLength 32
     */
  scene: string;
}
