/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { IdRequest } from './idRequest';

export type GetTicketByIdParams = {
req: IdRequest;
};
