/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 角色
 */
export type LoginUserUserRole = typeof LoginUserUserRole[keyof typeof LoginUserUserRole];


export const LoginUserUserRole = {
  user: 'user',
  admin: 'admin',
  inspector: 'inspector',
  disposer: 'disposer',
  ban: 'ban',
} as const;
