/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { LoginUserUserRole } from './loginUserUserRole';

export interface LoginUser {
  /** ID */
  id?: string;
  /** 账号 */
  userAccount?: string;
  /** 昵称 */
  userNickname?: string;
  /** 性别 */
  userGender?: string;
  /** 生日 */
  userBirthDate?: string;
  /** 头像 */
  userAvatar?: string;
  /** 简介 */
  userProfile?: string;
  /** 手机号 */
  userPhone?: string;
  /** 邮箱 */
  userEmail?: string;
  /** 角色 */
  userRole?: LoginUserUserRole;
  /** 创建时间 */
  createTime?: string;
  /** 更新时间 */
  updateTime?: string;
  /** Token */
  token?: string;
}
