/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 排序方向
 */
export type NaturalWeatherQueryRequestSortOrder = typeof NaturalWeatherQueryRequestSortOrder[keyof typeof NaturalWeatherQueryRequestSortOrder];


export const NaturalWeatherQueryRequestSortOrder = {
  ascend: 'ascend',
  descend: 'descend',
} as const;
