/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { NaturalWeatherQueryRequestSortOrder } from './naturalWeatherQueryRequestSortOrder';

export interface NaturalWeatherQueryRequest {
  /**
     * 页码
     * @minimum 1
     */
  current?: number;
  /**
     * 分页大小
     * @minimum 1
     * @maximum 100
     */
  pageSize?: number;
  /** 排序字段 */
  sortField?: string;
  /** 排序方向 */
  sortOrder?: NaturalWeatherQueryRequestSortOrder;
  /** 搜索关键词 */
  search?: string;
  /** 气象记录 ID */
  id?: string;
  /** 查询日期 (yyyy-MM-dd) */
  weatherTime?: string;
}
