/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface NaturalWeather {
  /** ID */
  id?: string;
  /** 创建时间 */
  createTime?: string;
  /** 更新时间 */
  updateTime?: string;
  /** 记录时间 */
  weatherTime?: string;
  /** 温度(℃) */
  temp?: number;
  /** 湿度(%) */
  humidity?: number;
  /** 气压(hPa) */
  pressure?: number;
  /** 风速(m/s) */
  windSpeed?: number;
  /** 风向角(0-360) */
  windDeg?: number;
  /** 降水量(mm) */
  rain?: number;
}
