/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface NaturalDisasters {
  /** ID */
  id?: string;
  /** 创建时间 */
  createTime?: string;
  /** 更新时间 */
  updateTime?: string;
  /** 开始时间 */
  disastersStartTime?: string;
  /** 预期结束 */
  disastersEndTime?: string;
  /** 标题 */
  disastersTitle?: string;
  /** 严重程度 */
  disastersSeverity?: string;
  /** 详细描述 */
  disastersDescription?: string;
}
