/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface NaturalWeatherAddRequest {
  /** 气象数据记录时间 */
  weatherTime: string;
  /**
     * 温度 (摄氏度)
     * @minimum -100
     * @maximum 100
     */
  temp?: number;
  /**
     * 相对湿度 (%)
     * @minimum 0
     * @maximum 100
     */
  humidity?: number;
  /**
     * 气压 (hPa)
     * @minimum 0
     */
  pressure?: number;
  /**
     * 风速 (m/s)
     * @minimum 0
     */
  windSpeed?: number;
  /**
     * 风向 (0-360度)
     * @minimum 0
     * @maximum 360
     */
  windDeg?: number;
  /**
     * 1小时降水量 (mm)
     * @minimum 0
     */
  rain?: number;
}
