/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 排序方向
 */
export type NaturalDisastersQueryRequestSortOrder = typeof NaturalDisastersQueryRequestSortOrder[keyof typeof NaturalDisastersQueryRequestSortOrder];


export const NaturalDisastersQueryRequestSortOrder = {
  ascend: 'ascend',
  descend: 'descend',
} as const;
