/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { NaturalDisastersQueryRequestSortOrder } from './naturalDisastersQueryRequestSortOrder';

export interface NaturalDisastersQueryRequest {
  /**
     * 页码
     * @minimum 1
     */
  current?: number;
  /**
     * 分页大小
     * @minimum 1
     * @maximum 100
     */
  pageSize?: number;
  /** 排序字段 */
  sortField?: string;
  /** 排序方向 */
  sortOrder?: NaturalDisastersQueryRequestSortOrder;
  /** 搜索关键词 */
  search?: string;
  /** 灾害 ID */
  id?: string;
  /** 查询起始日期 (yyyy-MM-dd) */
  disastersStartTime?: string;
  /** 查询结束日期 (yyyy-MM-dd) */
  disastersEndTime?: string;
  /** 灾害标题关键词 */
  disastersTitle?: string;
  /** 严重程度 */
  disastersSeverity?: string;
  /** 灾害描述关键词 */
  disastersDescription?: string;
}
