/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface NaturalDisastersUpdateRequest {
  /**
     * ID
     * @minLength 1
     */
  id: string;
  /** 灾害开始时间 */
  disastersStartTime?: string;
  /** 预期结束时间 */
  disastersEndTime?: string;
  /**
     * 灾害标题
     * @minLength 0
     * @maxLength 100
     */
  disastersTitle?: string;
  /**
     * 严重程度
     * @minLength 0
     * @maxLength 32
     */
  disastersSeverity?: string;
  /**
     * 灾害说明
     * @minLength 0
     * @maxLength 1000
     */
  disastersDescription?: string;
}
