/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface NaturalWeatherUpdateRequest {
  /**
     * ID
     * @minLength 1
     */
  id: string;
  /** 记录生效时间 */
  weatherTime?: string;
  /**
     * 温度 (摄氏度)
     * @minimum -100
     * @maximum 100
     */
  temp?: number;
  /**
     * 相对湿度 (%)
     * @minimum 0
     * @maximum 100
     */
  humidity?: number;
  /** 气压 (hPa) */
  pressure?: number;
  /** 风速 (m/s) */
  windSpeed?: number;
  /** 风向 (度) */
  windDeg?: number;
  /** 1小时内降水量 (mm) */
  rain?: number;
}
