/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 订单当前状态：pending_payment(待支付)/paid(已支付)/completed(已完成)/cancelled(已取消)/refunded(已退款)
 */
export type OrderQueryRequestOrderStatus = typeof OrderQueryRequestOrderStatus[keyof typeof OrderQueryRequestOrderStatus];


export const OrderQueryRequestOrderStatus = {
  pending_payment: 'pending_payment',
  paid: 'paid',
  completed: 'completed',
  cancelled: 'cancelled',
  refunded: 'refunded',
} as const;
