/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderItem } from './orderItem';
import type { OrderOrderStatus } from './orderOrderStatus';
import type { User } from './user';

export interface Order {
  /** ID */
  id?: string;
  /** 创建时间 */
  createTime?: string;
  /** 更新时间 */
  updateTime?: string;
  /** 总价格 */
  totalPrice?: number;
  /** 订单状态 */
  orderStatus?: OrderOrderStatus;
  /** 游览日期 */
  visitDate?: string;
  /** 联系人姓名 */
  contactName?: string;
  /** 联系人电话 */
  contactPhone?: string;
  /** 订单项列表 */
  orderItems?: OrderItem[];
  /** 下单用户信息 */
  user?: User;
}
