/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderQueryRequestOrderStatus } from './orderQueryRequestOrderStatus';
import type { OrderQueryRequestSortOrder } from './orderQueryRequestSortOrder';

export interface OrderQueryRequest {
  /**
     * 页码
     * @minimum 1
     */
  current?: number;
  /**
     * 分页大小
     * @minimum 1
     * @maximum 100
     */
  pageSize?: number;
  /** 排序字段 */
  sortField?: string;
  /** 排序方向 */
  sortOrder?: OrderQueryRequestSortOrder;
  /** 搜索关键词 */
  search?: string;
  /** 订单 ID */
  id?: string;
  /** 下单用户 ID (管理员过滤用) */
  userId?: string;
  /** 订单当前状态：pending_payment(待支付)/paid(已支付)/completed(已完成)/cancelled(已取消)/refunded(已退款) */
  orderStatus?: OrderQueryRequestOrderStatus;
  /** 联系人姓名关键词 (模糊匹配) */
  contactName?: string;
  /** 联系人电话关键词 (模糊匹配) */
  contactPhone?: string;
  /** 游览日期过滤 (yyyy-MM-dd) */
  visitDate?: string;
}
