/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderUpdateRequestOrderStatus } from './orderUpdateRequestOrderStatus';

export interface OrderUpdateRequest {
  /**
     * 修改的订单 ID
     * @minLength 1
     */
  id: string;
  /**
     * 订单总价格 (通常用于手动调价)
     * @minimum 0.01
     */
  totalPrice?: number;
  /** 订单状态变更目标值：pending_payment(待支付)/paid(已支付)/completed(已完成)/cancelled(已取消)/refunded(已退款) */
  orderStatus?: OrderUpdateRequestOrderStatus;
  /**
     * 联系人姓名修改
     * @minLength 0
     * @maxLength 32
     */
  contactName?: string;
  /**
     * 联系人电话修改
     * @pattern ^1[3-9]\d{9}$
     */
  contactPhone?: string;
  /** 修改后的游览日期 (yyyy-MM-dd) */
  visitDate?: string;
}
