/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface OrderItemAddRequest {
  /**
     * 门票资源 ID
     * @minLength 1
     */
  ticketId: string;
  /**
     * 购买张数
     * @minimum 1
     */
  quantity: number;
}
