/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 订单状态
 */
export type OrderOrderStatus = typeof OrderOrderStatus[keyof typeof OrderOrderStatus];


export const OrderOrderStatus = {
  pending_payment: 'pending_payment',
  paid: 'paid',
  completed: 'completed',
  cancelled: 'cancelled',
  refunded: 'refunded',
} as const;
