/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 排序方向
 */
export type OrderQueryRequestSortOrder = typeof OrderQueryRequestSortOrder[keyof typeof OrderQueryRequestSortOrder];


export const OrderQueryRequestSortOrder = {
  ascend: 'ascend',
  descend: 'descend',
} as const;
