/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderItemAddRequest } from './orderItemAddRequest';

export interface OrderAddRequest {
  /** 计划游览日期 (yyyy-MM-dd) */
  visitDate: string;
  /**
     * 订单联系人姓名
     * @minLength 0
     * @maxLength 32
     */
  contactName: string;
  /**
     * 订单联系人电话
     * @minLength 1
     * @pattern ^1[3-9]\d{9}$
     */
  contactPhone: string;
  /**
     * 订单包含的门票项列表
     * @minItems 1
     */
  items: OrderItemAddRequest[];
}
