/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Order } from './order';
import type { OrderItem } from './orderItem';
import type { PageOrder as __PageOrder } from './pageOrder';

export interface PageOrder {
  records?: Order[];
  total?: number;
  size?: number;
  current?: number;
  orders?: OrderItem[];
  optimizeCountSql?: __PageOrder;
  searchCount?: __PageOrder;
  optimizeJoinOfCountSql?: boolean;
  maxLimit?: number;
  countId?: string;
  /** @deprecated */
  pages?: number;
}
