/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderItem } from './orderItem';
import type { PageTaskCheckin as __PageTaskCheckin } from './pageTaskCheckin';
import type { TaskCheckin } from './taskCheckin';

export interface PageTaskCheckin {
  records?: TaskCheckin[];
  total?: number;
  size?: number;
  current?: number;
  orders?: OrderItem[];
  optimizeCountSql?: __PageTaskCheckin;
  searchCount?: __PageTaskCheckin;
  optimizeJoinOfCountSql?: boolean;
  maxLimit?: number;
  countId?: string;
  /** @deprecated */
  pages?: number;
}
