/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AttractionsRoute } from './attractionsRoute';
import type { OrderItem } from './orderItem';
import type { PageAttractionsRoute as __PageAttractionsRoute } from './pageAttractionsRoute';

export interface PageAttractionsRoute {
  records?: AttractionsRoute[];
  total?: number;
  size?: number;
  current?: number;
  orders?: OrderItem[];
  optimizeCountSql?: __PageAttractionsRoute;
  searchCount?: __PageAttractionsRoute;
  optimizeJoinOfCountSql?: boolean;
  maxLimit?: number;
  countId?: string;
  /** @deprecated */
  pages?: number;
}
