/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderItem } from './orderItem';
import type { PageUser as __PageUser } from './pageUser';
import type { User } from './user';

export interface PageUser {
  records?: User[];
  total?: number;
  size?: number;
  current?: number;
  orders?: OrderItem[];
  optimizeCountSql?: __PageUser;
  searchCount?: __PageUser;
  optimizeJoinOfCountSql?: boolean;
  maxLimit?: number;
  countId?: string;
  /** @deprecated */
  pages?: number;
}
