/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderItem } from './orderItem';
import type { PageTaskTrack as __PageTaskTrack } from './pageTaskTrack';
import type { TaskTrack } from './taskTrack';

export interface PageTaskTrack {
  records?: TaskTrack[];
  total?: number;
  size?: number;
  current?: number;
  orders?: OrderItem[];
  optimizeCountSql?: __PageTaskTrack;
  searchCount?: __PageTaskTrack;
  optimizeJoinOfCountSql?: boolean;
  maxLimit?: number;
  countId?: string;
  /** @deprecated */
  pages?: number;
}
