/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { NaturalDisasters } from './naturalDisasters';
import type { OrderItem } from './orderItem';
import type { PageNaturalDisasters as __PageNaturalDisasters } from './pageNaturalDisasters';

export interface PageNaturalDisasters {
  records?: NaturalDisasters[];
  total?: number;
  size?: number;
  current?: number;
  orders?: OrderItem[];
  optimizeCountSql?: __PageNaturalDisasters;
  searchCount?: __PageNaturalDisasters;
  optimizeJoinOfCountSql?: boolean;
  maxLimit?: number;
  countId?: string;
  /** @deprecated */
  pages?: number;
}
