/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderItem } from './orderItem';
import type { PagePublicizeWxPlatform as __PagePublicizeWxPlatform } from './pagePublicizeWxPlatform';
import type { PublicizeWxPlatform } from './publicizeWxPlatform';

export interface PagePublicizeWxPlatform {
  records?: PublicizeWxPlatform[];
  total?: number;
  size?: number;
  current?: number;
  orders?: OrderItem[];
  optimizeCountSql?: __PagePublicizeWxPlatform;
  searchCount?: __PagePublicizeWxPlatform;
  optimizeJoinOfCountSql?: boolean;
  maxLimit?: number;
  countId?: string;
  /** @deprecated */
  pages?: number;
}
