/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AiChatSessionSummary } from './aiChatSessionSummary';
import type { OrderItem } from './orderItem';
import type { PageAiChatSessionSummary as __PageAiChatSessionSummary } from './pageAiChatSessionSummary';

export interface PageAiChatSessionSummary {
  records?: AiChatSessionSummary[];
  total?: number;
  size?: number;
  current?: number;
  orders?: OrderItem[];
  optimizeCountSql?: __PageAiChatSessionSummary;
  searchCount?: __PageAiChatSessionSummary;
  optimizeJoinOfCountSql?: boolean;
  maxLimit?: number;
  countId?: string;
  /** @deprecated */
  pages?: number;
}
