/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { NaturalWeather } from './naturalWeather';
import type { OrderItem } from './orderItem';
import type { PageNaturalWeather as __PageNaturalWeather } from './pageNaturalWeather';

export interface PageNaturalWeather {
  records?: NaturalWeather[];
  total?: number;
  size?: number;
  current?: number;
  orders?: OrderItem[];
  optimizeCountSql?: __PageNaturalWeather;
  searchCount?: __PageNaturalWeather;
  optimizeJoinOfCountSql?: boolean;
  maxLimit?: number;
  countId?: string;
  /** @deprecated */
  pages?: number;
}
