/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderItem } from './orderItem';
import type { PageTaskInspection as __PageTaskInspection } from './pageTaskInspection';
import type { TaskInspection } from './taskInspection';

export interface PageTaskInspection {
  records?: TaskInspection[];
  total?: number;
  size?: number;
  current?: number;
  orders?: OrderItem[];
  optimizeCountSql?: __PageTaskInspection;
  searchCount?: __PageTaskInspection;
  optimizeJoinOfCountSql?: boolean;
  maxLimit?: number;
  countId?: string;
  /** @deprecated */
  pages?: number;
}
