/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Attractions } from './attractions';
import type { OrderItem } from './orderItem';
import type { PageAttractions as __PageAttractions } from './pageAttractions';

export interface PageAttractions {
  records?: Attractions[];
  total?: number;
  size?: number;
  current?: number;
  orders?: OrderItem[];
  optimizeCountSql?: __PageAttractions;
  searchCount?: __PageAttractions;
  optimizeJoinOfCountSql?: boolean;
  maxLimit?: number;
  countId?: string;
  /** @deprecated */
  pages?: number;
}
