/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderItem } from './orderItem';
import type { PageTicket as __PageTicket } from './pageTicket';
import type { Ticket } from './ticket';

export interface PageTicket {
  records?: Ticket[];
  total?: number;
  size?: number;
  current?: number;
  orders?: OrderItem[];
  optimizeCountSql?: __PageTicket;
  searchCount?: __PageTicket;
  optimizeJoinOfCountSql?: boolean;
  maxLimit?: number;
  countId?: string;
  /** @deprecated */
  pages?: number;
}
