/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderItem } from './orderItem';
import type { PagePublicizeVideo as __PagePublicizeVideo } from './pagePublicizeVideo';
import type { PublicizeVideo } from './publicizeVideo';

export interface PagePublicizeVideo {
  records?: PublicizeVideo[];
  total?: number;
  size?: number;
  current?: number;
  orders?: OrderItem[];
  optimizeCountSql?: __PagePublicizeVideo;
  searchCount?: __PagePublicizeVideo;
  optimizeJoinOfCountSql?: boolean;
  maxLimit?: number;
  countId?: string;
  /** @deprecated */
  pages?: number;
}
