/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderItem } from './orderItem';
import type { PageTaskDisposal as __PageTaskDisposal } from './pageTaskDisposal';
import type { TaskDisposal } from './taskDisposal';

export interface PageTaskDisposal {
  records?: TaskDisposal[];
  total?: number;
  size?: number;
  current?: number;
  orders?: OrderItem[];
  optimizeCountSql?: __PageTaskDisposal;
  searchCount?: __PageTaskDisposal;
  optimizeJoinOfCountSql?: boolean;
  maxLimit?: number;
  countId?: string;
  /** @deprecated */
  pages?: number;
}
