/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PublicizeWxPlatformQueryRequestSortOrder } from './publicizeWxPlatformQueryRequestSortOrder';

export interface PublicizeWxPlatformQueryRequest {
  /**
     * 页码
     * @minimum 1
     */
  current?: number;
  /**
     * 分页大小
     * @minimum 1
     * @maximum 100
     */
  pageSize?: number;
  /** 排序字段 */
  sortField?: string;
  /** 排序方向 */
  sortOrder?: PublicizeWxPlatformQueryRequestSortOrder;
  /** 搜索关键词 */
  search?: string;
  /** 微信文章记录 ID */
  id?: string;
  /** 文章标题关键词 */
  wxTitle?: string;
  /** 推文链接地址关键词 */
  wxUrl?: string;
  /** 推文描述信息关键词 */
  wxDescription?: string;
}
