/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 排序方向
 */
export type PublicizeVideoQueryRequestSortOrder = typeof PublicizeVideoQueryRequestSortOrder[keyof typeof PublicizeVideoQueryRequestSortOrder];


export const PublicizeVideoQueryRequestSortOrder = {
  ascend: 'ascend',
  descend: 'descend',
} as const;
