/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PublicizeVideoUpdateRequest {
  /**
     * 更新的视频 ID
     * @minLength 1
     */
  id: string;
  /**
     * 视频标题
     * @minLength 0
     * @maxLength 100
     */
  videoTitle?: string;
  /**
     * 视频地址 (URL)
     * @minLength 0
     * @maxLength 1024
     */
  videoUrl?: string;
  /**
     * 视频内容描述
     * @minLength 0
     * @maxLength 2000
     */
  videoDescription?: string;
}
