/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { User } from './user';

export interface PublicizeWxPlatform {
  /** ID */
  id?: string;
  /** 创建时间 */
  createTime?: string;
  /** 更新时间 */
  updateTime?: string;
  /** 标题 */
  wxTitle?: string;
  /** 链接 */
  wxUrl?: string;
  /** 详细描述 */
  wxDescription?: string;
  /** 发布人 */
  user?: User;
}
