/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PublicizeVideoQueryRequestSortOrder } from './publicizeVideoQueryRequestSortOrder';

export interface PublicizeVideoQueryRequest {
  /**
     * 页码
     * @minimum 1
     */
  current?: number;
  /**
     * 分页大小
     * @minimum 1
     * @maximum 100
     */
  pageSize?: number;
  /** 排序字段 */
  sortField?: string;
  /** 排序方向 */
  sortOrder?: PublicizeVideoQueryRequestSortOrder;
  /** 搜索关键词 */
  search?: string;
  /** 视频 ID */
  id?: string;
  /** 视频标题关键词 */
  videoTitle?: string;
  /** 视频地址 (支持模糊搜索) */
  videoUrl?: string;
  /** 视频描述关键词 */
  videoDescription?: string;
}
