/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PublicizeWxPlatformUpdateRequest {
  /**
     * 要更新的微信推文记录 ID
     * @minLength 1
     */
  id: string;
  /**
     * 推文标题
     * @minLength 0
     * @maxLength 100
     */
  wxTitle?: string;
  /**
     * 推文链接地址 (URL)
     * @minLength 0
     * @maxLength 1024
     */
  wxUrl?: string;
  /**
     * 推文详细描述内
     * @minLength 0
     * @maxLength 2000
     */
  wxDescription?: string;
}
