/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { User } from './user';

export interface PublicizeVideo {
  /** ID */
  id?: string;
  /** 创建时间 */
  createTime?: string;
  /** 更新时间 */
  updateTime?: string;
  /** 标题 */
  videoTitle?: string;
  /** 地址 */
  videoUrl?: string;
  /** 详细描述 */
  videoDescription?: string;
  /** 发布人 */
  user?: User;
}
