/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PublicizeWxPlatformAddRequest {
  /**
     * 微信推文标题
     * @minLength 0
     * @maxLength 100
     */
  wxTitle: string;
  /**
     * 微信公众号推文链接 (URL)
     * @minLength 0
     * @maxLength 1024
     */
  wxUrl: string;
  /**
     * 推文详细描述内容
     * @minLength 0
     * @maxLength 2000
     */
  wxDescription?: string;
}
