/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PagePublicizeWxPlatform } from './pagePublicizeWxPlatform';

export interface ResultPagePublicizeWxPlatform {
  code?: number;
  message?: string;
  data?: PagePublicizeWxPlatform;
  timestamp?: string;
}
