/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { LoginUser } from './loginUser';

export interface ResultLoginUser {
  code?: number;
  message?: string;
  data?: LoginUser;
  timestamp?: string;
}
