/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PublicizeWxPlatform } from './publicizeWxPlatform';

export interface ResultPublicizeWxPlatform {
  code?: number;
  message?: string;
  data?: PublicizeWxPlatform;
  timestamp?: string;
}
