/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserNotificationSettingVO } from './userNotificationSettingVO';

export interface ResultUserNotificationSettingVO {
  code?: number;
  message?: string;
  data?: UserNotificationSettingVO;
  timestamp?: string;
}
