/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AiChatMessage } from './aiChatMessage';

export interface ResultListAiChatMessage {
  code?: number;
  message?: string;
  data?: AiChatMessage[];
  timestamp?: string;
}
