/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageNaturalWeather } from './pageNaturalWeather';

export interface ResultPageNaturalWeather {
  code?: number;
  message?: string;
  data?: PageNaturalWeather;
  timestamp?: string;
}
