/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TaskInspection } from './taskInspection';

export interface ResultTaskInspection {
  code?: number;
  message?: string;
  data?: TaskInspection;
  timestamp?: string;
}
