/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { NaturalWeather } from './naturalWeather';

export interface ResultNaturalWeather {
  code?: number;
  message?: string;
  data?: NaturalWeather;
  timestamp?: string;
}
