/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Ticket } from './ticket';

export interface ResultTicket {
  code?: number;
  message?: string;
  data?: Ticket;
  timestamp?: string;
}
