/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageAttractionsRoute } from './pageAttractionsRoute';

export interface ResultPageAttractionsRoute {
  code?: number;
  message?: string;
  data?: PageAttractionsRoute;
  timestamp?: string;
}
