/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ResultVoid {
  code?: number;
  message?: string;
  data?: unknown;
  timestamp?: string;
}
