/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AttractionsType } from './attractionsType';

export interface ResultListAttractionsType {
  code?: number;
  message?: string;
  data?: AttractionsType[];
  timestamp?: string;
}
