/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageNaturalDisasters } from './pageNaturalDisasters';

export interface ResultPageNaturalDisasters {
  code?: number;
  message?: string;
  data?: PageNaturalDisasters;
  timestamp?: string;
}
