/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageUser } from './pageUser';

export interface ResultPageUser {
  code?: number;
  message?: string;
  data?: PageUser;
  timestamp?: string;
}
