/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageTicket } from './pageTicket';

export interface ResultPageTicket {
  code?: number;
  message?: string;
  data?: PageTicket;
  timestamp?: string;
}
