/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageOrder } from './pageOrder';

export interface ResultPageOrder {
  code?: number;
  message?: string;
  data?: PageOrder;
  timestamp?: string;
}
