/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageAttractions } from './pageAttractions';

export interface ResultPageAttractions {
  code?: number;
  message?: string;
  data?: PageAttractions;
  timestamp?: string;
}
