/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { NaturalDisasters } from './naturalDisasters';

export interface ResultNaturalDisasters {
  code?: number;
  message?: string;
  data?: NaturalDisasters;
  timestamp?: string;
}
