/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Attractions } from './attractions';

export interface ResultAttractions {
  code?: number;
  message?: string;
  data?: Attractions;
  timestamp?: string;
}
