/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageTaskDisposal } from './pageTaskDisposal';

export interface ResultPageTaskDisposal {
  code?: number;
  message?: string;
  data?: PageTaskDisposal;
  timestamp?: string;
}
