/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PublicizeVideo } from './publicizeVideo';

export interface ResultPublicizeVideo {
  code?: number;
  message?: string;
  data?: PublicizeVideo;
  timestamp?: string;
}
