/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageTaskTrack } from './pageTaskTrack';

export interface ResultPageTaskTrack {
  code?: number;
  message?: string;
  data?: PageTaskTrack;
  timestamp?: string;
}
