/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageTaskCheckin } from './pageTaskCheckin';

export interface ResultPageTaskCheckin {
  code?: number;
  message?: string;
  data?: PageTaskCheckin;
  timestamp?: string;
}
