/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageAiChatSessionSummary } from './pageAiChatSessionSummary';

export interface ResultPageAiChatSessionSummary {
  code?: number;
  message?: string;
  data?: PageAiChatSessionSummary;
  timestamp?: string;
}
