/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AiChatSessionSummary } from './aiChatSessionSummary';

export interface ResultAiChatSessionSummary {
  code?: number;
  message?: string;
  data?: AiChatSessionSummary;
  timestamp?: string;
}
