/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TaskDisposal } from './taskDisposal';

export interface ResultTaskDisposal {
  code?: number;
  message?: string;
  data?: TaskDisposal;
  timestamp?: string;
}
