/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TaskTrackDetail } from './taskTrackDetail';

export interface ResultTaskTrackDetail {
  code?: number;
  message?: string;
  data?: TaskTrackDetail;
  timestamp?: string;
}
