/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { User } from './user';

export interface ResultUser {
  code?: number;
  message?: string;
  data?: User;
  timestamp?: string;
}
