/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SysAdminSettingVO } from './sysAdminSettingVO';

export interface ResultSysAdminSettingVO {
  code?: number;
  message?: string;
  data?: SysAdminSettingVO;
  timestamp?: string;
}
