/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageTaskInspection } from './pageTaskInspection';

export interface ResultPageTaskInspection {
  code?: number;
  message?: string;
  data?: PageTaskInspection;
  timestamp?: string;
}
