/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface RouteItemAddRequest {
  /**
     * 景点 ID
     * @minLength 1
     */
  attractionsId: string;
  /** 排序权重 */
  sortOrder?: number;
  /**
     * 停靠备注
     * @minLength 0
     * @maxLength 512
     */
  stopNote?: string;
  /** 预计在此停留时间 (分钟) */
  estimatedStayMinutes?: number;
}
