/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface SysAdminSettingVO {
  /** 是否开放用户注册 */
  registerEnabled?: boolean;
  /** 灾害预警同步 Cron（秒 分 时 日 月 周） */
  cronDisaster?: string;
  /** 天气同步 Cron */
  cronWeather?: string;
  /** 每日巡查任务派发 Cron */
  cronInspection?: string;
  /** 轨迹超时扫描 Cron */
  cronTrack?: string;
}
