/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface SysAdminSettingUpdateRequest {
  /** 是否开放用户注册，不传则保持原值 */
  registerEnabled?: boolean;
  /** 灾害预警同步 Cron（6 域含秒）；不传保持原值，传空字符串表示关闭该任务 */
  cronDisaster?: string;
  /** 天气同步 Cron；不传保持原值，传空字符串表示关闭该任务 */
  cronWeather?: string;
  /** 每日巡查任务派发 Cron；不传保持原值，传空字符串表示关闭该任务 */
  cronInspection?: string;
  /** 轨迹超时扫描 Cron；不传保持原值，传空字符串表示关闭该任务 */
  cronTrack?: string;
}
