/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TaskDisposalQueryRequestDisposalStatus } from './taskDisposalQueryRequestDisposalStatus';
import type { TaskDisposalQueryRequestSortOrder } from './taskDisposalQueryRequestSortOrder';

export interface TaskDisposalQueryRequest {
  /**
     * 页码
     * @minimum 1
     */
  current?: number;
  /**
     * 分页大小
     * @minimum 1
     * @maximum 100
     */
  pageSize?: number;
  /** 排序字段 */
  sortField?: string;
  /** 排序方向 */
  sortOrder?: TaskDisposalQueryRequestSortOrder;
  /** 搜索关键词 */
  search?: string;
  /** 处置任务 ID */
  id?: string;
  /** 关联巡查任务 ID */
  inspectionTaskId?: string;
  /** 处置员 ID */
  disposerId?: string;
  /** 关联的景点 ID (管理员过滤用) */
  attractionsId?: string;
  /** 任务记录日期 (yyyy-MM-dd) */
  taskDate?: string;
  /** 处置描述关键词 (模糊过滤) */
  disposalDescription?: string;
  /** 任务当前状态：in_progress(处理中)/completed(已完成)/timeout(已超时) */
  disposalStatus?: TaskDisposalQueryRequestDisposalStatus;
}
