/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 异常状态过滤：normal(正常)/abnormal(异常)/unknown(待确认)
 */
export type TaskInspectionQueryRequestAbnormalStatus = typeof TaskInspectionQueryRequestAbnormalStatus[keyof typeof TaskInspectionQueryRequestAbnormalStatus];


export const TaskInspectionQueryRequestAbnormalStatus = {
  unknown: 'unknown',
  normal: 'normal',
  abnormal: 'abnormal',
} as const;
