/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { User } from './user';

export interface TaskCheckin {
  /** ID */
  id?: string;
  /** 创建时间 */
  createTime?: string;
  /** 更新时间 */
  updateTime?: string;
  /** 经度 */
  checkinLng?: number;
  /** 纬度 */
  checkinLat?: number;
  /** 签到地址 */
  checkinAddress?: string;
  /** 签到用户 */
  user?: User;
}
