/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 任务状态跳转值：in_progress(工作中)/completed(已完成)
 */
export type TaskDisposalUpdateRequestDisposalStatus = typeof TaskDisposalUpdateRequestDisposalStatus[keyof typeof TaskDisposalUpdateRequestDisposalStatus];


export const TaskDisposalUpdateRequestDisposalStatus = {
  pending: 'pending',
  in_progress: 'in_progress',
  completed: 'completed',
  timeout: 'timeout',
} as const;
