/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 任务当前状态：in_progress(处理中)/completed(已完成)/timeout(已超时)
 */
export type TaskDisposalQueryRequestDisposalStatus = typeof TaskDisposalQueryRequestDisposalStatus[keyof typeof TaskDisposalQueryRequestDisposalStatus];


export const TaskDisposalQueryRequestDisposalStatus = {
  pending: 'pending',
  in_progress: 'in_progress',
  completed: 'completed',
  timeout: 'timeout',
} as const;
