/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TaskInspectionAddRequestAbnormalStatus } from './taskInspectionAddRequestAbnormalStatus';

export interface TaskInspectionAddRequest {
  /**
     * 关联景点 ID
     * @minLength 1
     */
  attractionsId: string;
  /**
     * 关联巡查员 ID
     * @minLength 1
     */
  inspectorId: string;
  /** 计划巡查日期 */
  taskDate: string;
  /**
     * 巡查凭证图片
     * @minLength 0
     * @maxLength 2000
     */
  inspectionImages?: string;
  /**
     * 巡查详细过程/异常描述
     * @minLength 0
     * @maxLength 1000
     */
  inspectionDescription?: string;
  /** 异常判定预设：normal(正常)/abnormal(异常)/unknown(未知) */
  abnormalStatus?: TaskInspectionAddRequestAbnormalStatus;
}
