/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 异常判定预设：normal(正常)/abnormal(异常)/unknown(未知)
 */
export type TaskInspectionAddRequestAbnormalStatus = typeof TaskInspectionAddRequestAbnormalStatus[keyof typeof TaskInspectionAddRequestAbnormalStatus];


export const TaskInspectionAddRequestAbnormalStatus = {
  unknown: 'unknown',
  normal: 'normal',
  abnormal: 'abnormal',
} as const;
