/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Attractions } from './attractions';
import type { TaskDisposalDisposalStatus } from './taskDisposalDisposalStatus';
import type { TaskInspection } from './taskInspection';
import type { User } from './user';

export interface TaskDisposal {
  /** ID */
  id?: string;
  /** 创建时间 */
  createTime?: string;
  /** 更新时间 */
  updateTime?: string;
  /** 关联的巡检任务 ID */
  inspectionTaskId?: string;
  /** 处置过程/结果图片 */
  disposalImages?: string;
  /** 处置详细说明描述 */
  disposalDescription?: string;
  /** 处置状态 */
  disposalStatus?: TaskDisposalDisposalStatus;
  /** 关联的景点详细信息 */
  attractions?: Attractions;
  /** 关联的巡检任务详情 */
  inspectionTask?: TaskInspection;
  /** 执行处置任务的用户信息 */
  disposer?: User;
}
