/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TaskInspectionUpdateRequestAbnormalStatus } from './taskInspectionUpdateRequestAbnormalStatus';
import type { TaskInspectionUpdateRequestTaskStatus } from './taskInspectionUpdateRequestTaskStatus';

export interface TaskInspectionUpdateRequest {
  /**
     * 巡查记录对象 ID
     * @minLength 1
     */
  id: string;
  /** 关联景点 ID */
  attractionsId?: string;
  /** 关联巡查员 ID */
  inspectorId?: string;
  /**
     * 巡查记录补充图片 (JSON 格式 URL)
     * @minLength 0
     * @maxLength 2000
     */
  inspectionImages?: string;
  /**
     * 补充巡查工作说明描述
     * @minLength 0
     * @maxLength 1000
     */
  inspectionDescription?: string;
  /** 最终异常判定结果：normal/abnormal */
  abnormalStatus?: TaskInspectionUpdateRequestAbnormalStatus;
  /** 任务进度状态跳转值：pending(待开始)/in_progress(巡查中)/waiting_disposal(待处置)/completed(已完成) */
  taskStatus?: TaskInspectionUpdateRequestTaskStatus;
}
