/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TaskTrackDetailTrackStatus } from './taskTrackDetailTrackStatus';
import type { TaskTrackPoint } from './taskTrackPoint';
import type { User } from './user';

export interface TaskTrackDetail {
  /** ID */
  id?: string;
  /** 创建时间 */
  createTime?: string;
  /** 更新时间 */
  updateTime?: string;
  /** 用户 ID */
  userId?: string;
  /** 开始时间 */
  trackStartTime?: string;
  /** 结束时间 */
  trackEndTime?: string;
  /** 轨迹状态 */
  trackStatus?: TaskTrackDetailTrackStatus;
  /** 用户信息 */
  user?: User;
  /** 点位列表 */
  points?: TaskTrackPoint[];
}
