/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 轨迹状态
 */
export type TaskTrackTrackStatus = typeof TaskTrackTrackStatus[keyof typeof TaskTrackTrackStatus];


export const TaskTrackTrackStatus = {
  running: 'running',
  finished: 'finished',
  interrupted: 'interrupted',
} as const;
