/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TaskDisposalAddRequest {
  /**
     * 关联的巡查任务 ID
     * @minLength 1
     */
  inspectionTaskId: string;
  /**
     * 指派的处置员 ID
     * @minLength 1
     */
  disposerId: string;
  /**
     * 处置凭证图片
     * @minLength 0
     * @maxLength 2000
     */
  disposalImages?: string;
  /**
     * 处置任务详细描述
     * @minLength 0
     * @maxLength 1000
     */
  disposalDescription?: string;
}
