/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 轨迹状态
 */
export type TaskTrackDetailTrackStatus = typeof TaskTrackDetailTrackStatus[keyof typeof TaskTrackDetailTrackStatus];


export const TaskTrackDetailTrackStatus = {
  running: 'running',
  finished: 'finished',
  interrupted: 'interrupted',
} as const;
