/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 最终异常判定结果：normal/abnormal
 */
export type TaskInspectionUpdateRequestAbnormalStatus = typeof TaskInspectionUpdateRequestAbnormalStatus[keyof typeof TaskInspectionUpdateRequestAbnormalStatus];


export const TaskInspectionUpdateRequestAbnormalStatus = {
  unknown: 'unknown',
  normal: 'normal',
  abnormal: 'abnormal',
} as const;
