/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 任务进度状态过滤：in_progress(巡查中)/waiting_disposal(待处置)/completed(已完成)/timeout(已超时)
 */
export type TaskInspectionQueryRequestTaskStatus = typeof TaskInspectionQueryRequestTaskStatus[keyof typeof TaskInspectionQueryRequestTaskStatus];


export const TaskInspectionQueryRequestTaskStatus = {
  in_progress: 'in_progress',
  waiting_disposal: 'waiting_disposal',
  completed: 'completed',
  timeout: 'timeout',
} as const;
