/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TaskTrackPoint {
  /** ID */
  id?: string;
  /** 创建时间 */
  createTime?: string;
  /** 更新时间 */
  updateTime?: string;
  /** 轨迹 ID */
  trackId?: string;
  /** 经度 */
  trackLng?: number;
  /** 纬度 */
  trackLat?: number;
  /** 记录时间戳 */
  trackTimestamp?: number;
}
