/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TaskInspectionQueryRequestAbnormalStatus } from './taskInspectionQueryRequestAbnormalStatus';
import type { TaskInspectionQueryRequestSortOrder } from './taskInspectionQueryRequestSortOrder';
import type { TaskInspectionQueryRequestTaskStatus } from './taskInspectionQueryRequestTaskStatus';

export interface TaskInspectionQueryRequest {
  /**
     * 页码
     * @minimum 1
     */
  current?: number;
  /**
     * 分页大小
     * @minimum 1
     * @maximum 100
     */
  pageSize?: number;
  /** 排序字段 */
  sortField?: string;
  /** 排序方向 */
  sortOrder?: TaskInspectionQueryRequestSortOrder;
  /** 搜索关键词 */
  search?: string;
  /** 巡检任务 ID */
  id?: string;
  /** 关联的景点 ID */
  attractionsId?: string;
  /** 关联的巡查员 ID */
  inspectorId?: string;
  /** 景点名称关键词 (支持跨表模糊搜素) */
  attractionsName?: string;
  /** 巡查详情描述关键词 */
  inspectionDescription?: string;
  /** 任务所属的具体日期 (yyyy-MM-dd) */
  taskDate?: string;
  /** 异常状态过滤：normal(正常)/abnormal(异常)/unknown(待确认) */
  abnormalStatus?: TaskInspectionQueryRequestAbnormalStatus;
  /** 任务进度状态过滤：in_progress(巡查中)/waiting_disposal(待处置)/completed(已完成)/timeout(已超时) */
  taskStatus?: TaskInspectionQueryRequestTaskStatus;
}
