/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TaskTrackPointAddRequest {
  /**
     * 关联的运行轨迹 ID
     * @minLength 1
     */
  trackId: string;
  /** 记录点的经度 */
  trackLng: number;
  /** 记录点的纬度 */
  trackLat: number;
}
