/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Attractions } from './attractions';
import type { TaskInspectionAbnormalStatus } from './taskInspectionAbnormalStatus';
import type { TaskInspectionTaskStatus } from './taskInspectionTaskStatus';
import type { User } from './user';

export interface TaskInspection {
  /** ID */
  id?: string;
  /** 创建时间 */
  createTime?: string;
  /** 更新时间 */
  updateTime?: string;
  /** 计划巡查日期 */
  taskDate?: string;
  /** 巡检图片 */
  inspectionImages?: string;
  /** 巡检详细描述 */
  inspectionDescription?: string;
  /** 异常状态 */
  abnormalStatus?: TaskInspectionAbnormalStatus;
  /** 任务状态 */
  taskStatus?: TaskInspectionTaskStatus;
  /** 关联景点详细信息 */
  attractions?: Attractions;
  /** 关联巡查员详细信息 */
  inspector?: User;
}
