/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 任务状态
 */
export type TaskInspectionTaskStatus = typeof TaskInspectionTaskStatus[keyof typeof TaskInspectionTaskStatus];


export const TaskInspectionTaskStatus = {
  in_progress: 'in_progress',
  waiting_disposal: 'waiting_disposal',
  completed: 'completed',
  timeout: 'timeout',
} as const;
