/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 处置状态
 */
export type TaskDisposalDisposalStatus = typeof TaskDisposalDisposalStatus[keyof typeof TaskDisposalDisposalStatus];


export const TaskDisposalDisposalStatus = {
  pending: 'pending',
  in_progress: 'in_progress',
  completed: 'completed',
  timeout: 'timeout',
} as const;
