/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 排序方向
 */
export type TaskCheckinQueryRequestSortOrder = typeof TaskCheckinQueryRequestSortOrder[keyof typeof TaskCheckinQueryRequestSortOrder];


export const TaskCheckinQueryRequestSortOrder = {
  ascend: 'ascend',
  descend: 'descend',
} as const;
