/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 异常状态
 */
export type TaskInspectionAbnormalStatus = typeof TaskInspectionAbnormalStatus[keyof typeof TaskInspectionAbnormalStatus];


export const TaskInspectionAbnormalStatus = {
  unknown: 'unknown',
  normal: 'normal',
  abnormal: 'abnormal',
} as const;
