/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TaskCheckinAddRequest {
  /**
     * 签到位置经度
     * @minimum -180
     * @maximum 180
     */
  checkinLng?: number;
  /**
     * 签到位置纬度
     * @minimum -90
     * @maximum 90
     */
  checkinLat?: number;
  /**
     * 签到详细地址名称
     * @minLength 0
     * @maxLength 255
     */
  checkinAddress: string;
}
