/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TaskCheckinQueryRequestSortOrder } from './taskCheckinQueryRequestSortOrder';

export interface TaskCheckinQueryRequest {
  /**
     * 页码
     * @minimum 1
     */
  current?: number;
  /**
     * 分页大小
     * @minimum 1
     * @maximum 100
     */
  pageSize?: number;
  /** 排序字段 */
  sortField?: string;
  /** 排序方向 */
  sortOrder?: TaskCheckinQueryRequestSortOrder;
  /** 搜索关键词 */
  search?: string;
  /** 打卡记录 ID */
  id?: string;
  /** 打卡用户 ID */
  userId?: string;
  /** 打卡地点关键词 (模糊过滤) */
  checkinAddress?: string;
  /** 打卡所属的具体日期 (yyyy-MM-dd) */
  createTime?: string;
}
