/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TaskDisposalUpdateRequestDisposalStatus } from './taskDisposalUpdateRequestDisposalStatus';

export interface TaskDisposalUpdateRequest {
  /**
     * 需要更新的对象 ID
     * @minLength 1
     */
  id: string;
  /**
     * 更新后的处置效果图 (JSON 格式 URL)
     * @minLength 0
     * @maxLength 2000
     */
  disposalImages?: string;
  /**
     * 补充的处置工作说明
     * @minLength 0
     * @maxLength 1000
     */
  disposalDescription?: string;
  /** 任务状态跳转值：in_progress(工作中)/completed(已完成) */
  disposalStatus?: TaskDisposalUpdateRequestDisposalStatus;
}
