/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TaskTrackQueryRequestSortOrder } from './taskTrackQueryRequestSortOrder';
import type { TaskTrackQueryRequestTrackStatus } from './taskTrackQueryRequestTrackStatus';

export interface TaskTrackQueryRequest {
  /**
     * 页码
     * @minimum 1
     */
  current?: number;
  /**
     * 分页大小
     * @minimum 1
     * @maximum 100
     */
  pageSize?: number;
  /** 排序字段 */
  sortField?: string;
  /** 排序方向 */
  sortOrder?: TaskTrackQueryRequestSortOrder;
  /** 搜索关键词 */
  search?: string;
  /** 用户 ID */
  userId?: string;
  /** 轨迹状态 */
  trackStatus?: TaskTrackQueryRequestTrackStatus;
  /** 巡查日期 */
  taskDate?: string;
}
