/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TicketTicketStatus } from './ticketTicketStatus';

export interface Ticket {
  /** ID */
  id?: string;
  /** 创建时间 */
  createTime?: string;
  /** 更新时间 */
  updateTime?: string;
  /** 门票名称 */
  ticketName?: string;
  /** 门票价格 */
  ticketPrice?: number;
  /** 门票详情描述 */
  ticketDescription?: string;
  /** 门票配图 URL */
  ticketImage?: string;
  /** 票据有效天数 */
  validDays?: number;
  /** 当前库存数量 */
  stockQuantity?: number;
  /** 门票状态 */
  ticketStatus?: TicketTicketStatus;
}
