/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 门票状态变更目标值
 */
export type TicketUpdateRequestTicketStatus = typeof TicketUpdateRequestTicketStatus[keyof typeof TicketUpdateRequestTicketStatus];


export const TicketUpdateRequestTicketStatus = {
  draft: 'draft',
  on_sale: 'on_sale',
  off_sale: 'off_sale',
} as const;
