/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TicketQueryRequestSortOrder } from './ticketQueryRequestSortOrder';
import type { TicketQueryRequestTicketStatus } from './ticketQueryRequestTicketStatus';

export interface TicketQueryRequest {
  /**
     * 页码
     * @minimum 1
     */
  current?: number;
  /**
     * 分页大小
     * @minimum 1
     * @maximum 100
     */
  pageSize?: number;
  /** 排序字段 */
  sortField?: string;
  /** 排序方向 */
  sortOrder?: TicketQueryRequestSortOrder;
  /** 搜索关键词 */
  search?: string;
  /** 门票记录 ID */
  id?: string;
  /** 门票名称关键词 (模糊匹配) */
  ticketName?: string;
  /** 门票描述关键词 (模糊匹配) */
  ticketDescription?: string;
  /** 门票当前状态过滤： draft/on_sale/off_sale */
  ticketStatus?: TicketQueryRequestTicketStatus;
}
