/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 门票当前状态过滤： draft/on_sale/off_sale
 */
export type TicketQueryRequestTicketStatus = typeof TicketQueryRequestTicketStatus[keyof typeof TicketQueryRequestTicketStatus];


export const TicketQueryRequestTicketStatus = {
  draft: 'draft',
  on_sale: 'on_sale',
  off_sale: 'off_sale',
} as const;
