/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TicketAddRequestTicketStatus } from './ticketAddRequestTicketStatus';

export interface TicketAddRequest {
  /**
     * 门票显示名称
     * @minLength 0
     * @maxLength 100
     */
  ticketName: string;
  /**
     * 门票单价 (元)
     * @minimum 0
     */
  ticketPrice: number;
  /**
     * 门票详细使用说明描述
     * @minLength 0
     * @maxLength 2000
     */
  ticketDescription?: string;
  /**
     * 门票展示图 URL
     * @minLength 0
     * @maxLength 1024
     */
  ticketImage?: string;
  /**
     * 自激活起有效天数 (单位：天)
     * @minimum 1
     */
  validDays: number;
  /**
     * 初始库存总数
     * @minimum 0
     */
  stockQuantity: number;
  /** 门票初始发布状态： draft(草稿)/on_sale(上架)/off_sale(下架) */
  ticketStatus?: TicketAddRequestTicketStatus;
}
