/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 门票状态
 */
export type TicketTicketStatus = typeof TicketTicketStatus[keyof typeof TicketTicketStatus];


export const TicketTicketStatus = {
  draft: 'draft',
  on_sale: 'on_sale',
  off_sale: 'off_sale',
} as const;
