/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 门票初始发布状态： draft(草稿)/on_sale(上架)/off_sale(下架)
 */
export type TicketAddRequestTicketStatus = typeof TicketAddRequestTicketStatus[keyof typeof TicketAddRequestTicketStatus];


export const TicketAddRequestTicketStatus = {
  draft: 'draft',
  on_sale: 'on_sale',
  off_sale: 'off_sale',
} as const;
