/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TicketUpdateRequestTicketStatus } from './ticketUpdateRequestTicketStatus';

export interface TicketUpdateRequest {
  /**
     * 需要更新的对象 ID
     * @minLength 1
     */
  id: string;
  /**
     * 门票名称修改
     * @minLength 0
     * @maxLength 100
     */
  ticketName?: string;
  /**
     * 门票单价修改 (元)
     * @minimum 0
     */
  ticketPrice?: number;
  /**
     * 门票描述修改
     * @minLength 0
     * @maxLength 2000
     */
  ticketDescription?: string;
  /**
     * 门票图片 URL 修改
     * @minLength 0
     * @maxLength 1024
     */
  ticketImage?: string;
  /** 有效时长天数修改 */
  validDays?: number;
  /** 库存总量修改 */
  stockQuantity?: number;
  /** 门票状态变更目标值 */
  ticketStatus?: TicketUpdateRequestTicketStatus;
}
