/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UploadFileParams = {
/**
 * 业务类型标识前缀（映射到 S3 bucket 目录）
 */
biz: string;
};
