/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserAddRequestUserRole } from './userAddRequestUserRole';

export interface UserAddRequest {
  /**
     * 用户登录账号
     * @minLength 4
     * @maxLength 32
     */
  userAccount: string;
  /**
     * 用户初始密码
     * @minLength 8
     * @maxLength 32
     */
  userPassword?: string;
  /**
     * 用户显示昵称
     * @minLength 0
     * @maxLength 32
     */
  userNickname?: string;
  /**
     * 手机号码
     * @pattern ^$|^1[3-9]\d{9}$
     */
  userPhone?: string;
  /**
     * 邮箱地址
     * @minLength 0
     * @maxLength 64
     */
  userEmail?: string;
  /**
     * 性别
     * @minLength 0
     * @maxLength 8
     */
  userGender?: string;
  /** 出生日期 (yyyy-MM-dd) */
  userBirthDate?: string;
  /**
     * 头像图片 URL
     * @minLength 0
     * @maxLength 1024
     */
  userAvatar?: string;
  /**
     * 个人自述简介
     * @minLength 0
     * @maxLength 512
     */
  userProfile?: string;
  /** 分配的用户角色：user/admin/inspector/disposer/ban */
  userRole?: UserAddRequestUserRole;
}
