/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserNotificationSettingVO {
  /** 每日巡查任务下发邮件 */
  notifyInspectionDispatch?: boolean;
  /** 处置任务分配邮件 */
  notifyDisposalAssigned?: boolean;
  /** 是否接收异常景点通知邮件（管理员按各自账号配置；非管理员可不展示） */
  notifyAbnormalToAdmin?: boolean;
}
