/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 用户角色过滤：user(普通用户)/admin(系统管理员)/inspector(巡查员)/disposer(处置员)/ban(封禁)
 */
export type UserQueryRequestUserRole = typeof UserQueryRequestUserRole[keyof typeof UserQueryRequestUserRole];


export const UserQueryRequestUserRole = {
  user: 'user',
  admin: 'admin',
  inspector: 'inspector',
  disposer: 'disposer',
  ban: 'ban',
} as const;
