/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserLoginRequest {
  /**
     * 账号
     * @minLength 4
     * @maxLength 32
     */
  userAccount: string;
  /**
     * 密码
     * @minLength 8
     * @maxLength 32
     */
  userPassword: string;
}
