/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 分配的用户角色：user/admin/inspector/disposer/ban
 */
export type UserAddRequestUserRole = typeof UserAddRequestUserRole[keyof typeof UserAddRequestUserRole];


export const UserAddRequestUserRole = {
  user: 'user',
  admin: 'admin',
  inspector: 'inspector',
  disposer: 'disposer',
  ban: 'ban',
} as const;
