/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserUpdateRequestUserRole } from './userUpdateRequestUserRole';

export interface UserUpdateRequest {
  /**
     * 修改的对象 ID
     * @minLength 1
     */
  id: string;
  /**
     * 修改登录账号
     * @minLength 4
     * @maxLength 32
     */
  userAccount?: string;
  /**
     * 强制修改密码
     * @minLength 8
     * @maxLength 32
     */
  userPassword?: string;
  /**
     * 修改昵称
     * @minLength 0
     * @maxLength 32
     */
  userNickname?: string;
  /**
     * 更换头像 URL
     * @minLength 0
     * @maxLength 1024
     */
  userAvatar?: string;
  /**
     * 修改个人自述
     * @minLength 0
     * @maxLength 512
     */
  userProfile?: string;
  /**
     * 修改手机号码
     * @minLength 0
     * @maxLength 16
     * @pattern ^$|^1[3-9]\d{9}$
     */
  userPhone?: string;
  /**
     * 修改邮箱地址
     * @minLength 0
     * @maxLength 64
     */
  userEmail?: string;
  /**
     * 修改性别
     * @minLength 0
     * @maxLength 8
     */
  userGender?: string;
  /** 修改出生日期 (yyyy-MM-dd) */
  userBirthDate?: string;
  /** 调整用户角色优先级 */
  userRole?: UserUpdateRequestUserRole;
}
