/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserQueryRequestSortOrder } from './userQueryRequestSortOrder';
import type { UserQueryRequestUserRole } from './userQueryRequestUserRole';

export interface UserQueryRequest {
  /**
     * 页码
     * @minimum 1
     */
  current?: number;
  /**
     * 分页大小
     * @minimum 1
     * @maximum 100
     */
  pageSize?: number;
  /** 排序字段 */
  sortField?: string;
  /** 排序方向 */
  sortOrder?: UserQueryRequestSortOrder;
  /** 搜索关键词 */
  search?: string;
  /** 用户 ID */
  id?: string;
  /** 用户昵称关键词 (模糊匹配) */
  userNickname?: string;
  /** 用户账号关键词 (模糊匹配) */
  userAccount?: string;
  /** 手机号关键词 (模糊匹配) */
  userPhone?: string;
  /** 邮箱地址关键词 (模糊匹配) */
  userEmail?: string;
  /** 用户角色过滤：user(普通用户)/admin(系统管理员)/inspector(巡查员)/disposer(处置员)/ban(封禁) */
  userRole?: UserQueryRequestUserRole;
}
