/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 系统角色
 */
export type UserUserRole = typeof UserUserRole[keyof typeof UserUserRole];


export const UserUserRole = {
  user: 'user',
  admin: 'admin',
  inspector: 'inspector',
  disposer: 'disposer',
  ban: 'ban',
} as const;
