/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 调整用户角色优先级
 */
export type UserUpdateRequestUserRole = typeof UserUpdateRequestUserRole[keyof typeof UserUpdateRequestUserRole];


export const UserUpdateRequestUserRole = {
  user: 'user',
  admin: 'admin',
  inspector: 'inspector',
  disposer: 'disposer',
  ban: 'ban',
} as const;
