/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserRegisterRequest {
  /**
     * 昵称
     * @minLength 0
     * @maxLength 32
     */
  userNickname?: string;
  /**
     * 性别
     * @minLength 0
     * @maxLength 8
     */
  userGender?: string;
  /** 出生日期 */
  userBirthDate?: string;
  /**
     * 账号
     * @minLength 4
     * @maxLength 32
     */
  userAccount: string;
  /**
     * 密码
     * @minLength 8
     * @maxLength 32
     */
  userPassword: string;
  /**
     * 验证码
     * @minLength 0
     * @maxLength 16
     */
  code: string;
  /**
     * 手机号
     * @pattern ^$|^1[3-9]\d{9}$
     */
  userPhone?: string;
  /**
     * 邮箱
     * @minLength 0
     * @maxLength 64
     */
  userEmail: string;
  /**
     * 头像
     * @minLength 0
     * @maxLength 1024
     */
  userAvatar?: string;
  /**
     * 简介
     * @minLength 0
     * @maxLength 512
     */
  userProfile?: string;
}
