/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserUpdateMyRequest {
  /**
     * 修改账号
     * @minLength 4
     * @maxLength 32
     */
  userAccount?: string;
  /**
     * 修改昵称
     * @minLength 0
     * @maxLength 32
     */
  userNickname?: string;
  /**
     * 修改性别
     * @minLength 0
     * @maxLength 8
     */
  userGender?: string;
  /** 修改生日 (yyyy-MM-dd) */
  userBirthDate?: string;
  /**
     * 更换头像 URL
     * @minLength 0
     * @maxLength 1024
     */
  userAvatar?: string;
  /**
     * 更新简介
     * @minLength 0
     * @maxLength 512
     */
  userProfile?: string;
  /**
     * 更新密码 (不填默认为旧密码)
     * @minLength 8
     * @maxLength 32
     */
  userPassword?: string;
  /**
     * 更新手机号
     * @pattern ^$|^1[3-9]\d{9}$
     */
  userPhone?: string;
  /**
     * 更新邮箱地址
     * @minLength 0
     * @maxLength 64
     */
  userEmail?: string;
  /**
     * 旧邮箱或旧手机验证码 (敏感字段修改必须)
     * @minLength 0
     * @maxLength 16
     */
  code?: string;
  /**
     * 新邮箱验证码 (换绑邮箱必须)
     * @minLength 0
     * @maxLength 16
     */
  emailCode?: string;
}
