/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserResetPasswordRequest {
  /**
     * 绑定的邮箱地址
     * @minLength 0
     * @maxLength 64
     */
  userEmail: string;
  /**
     * 设定的新密码 (8-32位)
     * @minLength 8
     * @maxLength 32
     */
  newPassword: string;
  /**
     * 邮箱验证码
     * @minLength 0
     * @maxLength 16
     */
  code: string;
}
