/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserUserRole } from './userUserRole';

export interface User {
  /** ID */
  id?: string;
  /** 创建时间 */
  createTime?: string;
  /** 更新时间 */
  updateTime?: string;
  /** 登录账号 */
  userAccount?: string;
  /** 显示昵称 */
  userNickname?: string;
  /** 头像 */
  userAvatar?: string;
  /** 简介 */
  userProfile?: string;
  /** 手机号 */
  userPhone?: string;
  /** 邮箱 */
  userEmail?: string;
  /** 性别 */
  userGender?: string;
  /** 生日 */
  userBirthDate?: string;
  /** 系统角色 */
  userRole?: UserUserRole;
}
