/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserNotificationSettingUpdateRequest {
  /** 每日巡查任务下发邮件，不传则保持原值 */
  notifyInspectionDispatch?: boolean;
  /** 处置任务分配邮件，不传则保持原值 */
  notifyDisposalAssigned?: boolean;
  /** 是否接收异常景点通知邮件（管理员），不传则保持原值 */
  notifyAbnormalToAdmin?: boolean;
}
