/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  GetInspectionTaskByIdParams,
  IdRequest,
  ResultBoolean,
  ResultPageTaskInspection,
  ResultString,
  ResultTaskInspection,
  TaskInspectionAddRequest,
  TaskInspectionQueryRequest,
  TaskInspectionUpdateRequest
} from '../../models';

import { mutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const updateInspectionTask = (
    taskInspectionUpdateRequest: TaskInspectionUpdateRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/task/inspection/update`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: taskInspectionUpdateRequest
    },
      options);
    }
  export const listInspectionTasksByPage = (
    taskInspectionQueryRequest: TaskInspectionQueryRequest,
 options?: SecondParameter<typeof mutator<ResultPageTaskInspection>>,) => {
      return mutator<ResultPageTaskInspection>(
      {url: `/api/task/inspection/list/page`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: taskInspectionQueryRequest
    },
      options);
    }
  export const deleteInspectionTask = (
    idRequest: IdRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/task/inspection/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: idRequest
    },
      options);
    }
  export const addInspectionTask = (
    taskInspectionAddRequest: TaskInspectionAddRequest,
 options?: SecondParameter<typeof mutator<ResultString>>,) => {
      return mutator<ResultString>(
      {url: `/api/task/inspection/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: taskInspectionAddRequest
    },
      options);
    }
  export const getInspectionTaskById = (
    params: GetInspectionTaskByIdParams,
 options?: SecondParameter<typeof mutator<ResultTaskInspection>>,) => {
      return mutator<ResultTaskInspection>(
      {url: `/api/task/inspection/get`, method: 'GET',
        params
    },
      options);
    }

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type UpdateInspectionTaskResult = NonNullable<Awaited<ReturnType<typeof updateInspectionTask>>>
export type ListInspectionTasksByPageResult = NonNullable<Awaited<ReturnType<typeof listInspectionTasksByPage>>>
export type DeleteInspectionTaskResult = NonNullable<Awaited<ReturnType<typeof deleteInspectionTask>>>
export type AddInspectionTaskResult = NonNullable<Awaited<ReturnType<typeof addInspectionTask>>>
export type GetInspectionTaskByIdResult = NonNullable<Awaited<ReturnType<typeof getInspectionTaskById>>>
