/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  ResultBoolean,
  ResultSysAdminSettingVO,
  SysAdminSettingUpdateRequest
} from '../../models';

import { mutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const updateSettings = (
    sysAdminSettingUpdateRequest: SysAdminSettingUpdateRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/admin/sys-setting/update`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sysAdminSettingUpdateRequest
    },
      options);
    }
  export const getSettings = (

 options?: SecondParameter<typeof mutator<ResultSysAdminSettingVO>>,) => {
      return mutator<ResultSysAdminSettingVO>(
      {url: `/api/admin/sys-setting/get`, method: 'GET'
    },
      options);
    }

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type UpdateSettingsResult = NonNullable<Awaited<ReturnType<typeof updateSettings>>>
export type GetSettingsResult = NonNullable<Awaited<ReturnType<typeof getSettings>>>
