/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  GetWxPlatformByIdParams,
  IdRequest,
  PublicizeWxPlatformAddRequest,
  PublicizeWxPlatformQueryRequest,
  PublicizeWxPlatformUpdateRequest,
  ResultBoolean,
  ResultPagePublicizeWxPlatform,
  ResultPublicizeWxPlatform,
  ResultString
} from '../../models';

import { mutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const updateWxPlatform = (
    publicizeWxPlatformUpdateRequest: PublicizeWxPlatformUpdateRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/publicize/wx/update`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: publicizeWxPlatformUpdateRequest
    },
      options);
    }
  export const listWxPlatformsByPage = (
    publicizeWxPlatformQueryRequest: PublicizeWxPlatformQueryRequest,
 options?: SecondParameter<typeof mutator<ResultPagePublicizeWxPlatform>>,) => {
      return mutator<ResultPagePublicizeWxPlatform>(
      {url: `/api/publicize/wx/list/page`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: publicizeWxPlatformQueryRequest
    },
      options);
    }
  export const deleteWxPlatform = (
    idRequest: IdRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/publicize/wx/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: idRequest
    },
      options);
    }
  export const addWxPlatform = (
    publicizeWxPlatformAddRequest: PublicizeWxPlatformAddRequest,
 options?: SecondParameter<typeof mutator<ResultString>>,) => {
      return mutator<ResultString>(
      {url: `/api/publicize/wx/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: publicizeWxPlatformAddRequest
    },
      options);
    }
  export const getWxPlatformById = (
    params: GetWxPlatformByIdParams,
 options?: SecondParameter<typeof mutator<ResultPublicizeWxPlatform>>,) => {
      return mutator<ResultPublicizeWxPlatform>(
      {url: `/api/publicize/wx/get`, method: 'GET',
        params
    },
      options);
    }

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type UpdateWxPlatformResult = NonNullable<Awaited<ReturnType<typeof updateWxPlatform>>>
export type ListWxPlatformsByPageResult = NonNullable<Awaited<ReturnType<typeof listWxPlatformsByPage>>>
export type DeleteWxPlatformResult = NonNullable<Awaited<ReturnType<typeof deleteWxPlatform>>>
export type AddWxPlatformResult = NonNullable<Awaited<ReturnType<typeof addWxPlatform>>>
export type GetWxPlatformByIdResult = NonNullable<Awaited<ReturnType<typeof getWxPlatformById>>>
