/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  AttractionsRouteAddRequest,
  AttractionsRouteQueryRequest,
  AttractionsRouteUpdateRequest,
  GetRouteByIdParams,
  IdRequest,
  ResultAttractionsRoute,
  ResultBoolean,
  ResultPageAttractionsRoute,
  ResultString
} from '../../models';

import { mutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const updateRoute = (
    attractionsRouteUpdateRequest: AttractionsRouteUpdateRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/attractions/route/update`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: attractionsRouteUpdateRequest
    },
      options);
    }
  export const listRoutesByPage = (
    attractionsRouteQueryRequest: AttractionsRouteQueryRequest,
 options?: SecondParameter<typeof mutator<ResultPageAttractionsRoute>>,) => {
      return mutator<ResultPageAttractionsRoute>(
      {url: `/api/attractions/route/list/page`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: attractionsRouteQueryRequest
    },
      options);
    }
  export const deleteRoute = (
    idRequest: IdRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/attractions/route/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: idRequest
    },
      options);
    }
  export const addRoute = (
    attractionsRouteAddRequest: AttractionsRouteAddRequest,
 options?: SecondParameter<typeof mutator<ResultString>>,) => {
      return mutator<ResultString>(
      {url: `/api/attractions/route/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: attractionsRouteAddRequest
    },
      options);
    }
  export const getRouteById = (
    params: GetRouteByIdParams,
 options?: SecondParameter<typeof mutator<ResultAttractionsRoute>>,) => {
      return mutator<ResultAttractionsRoute>(
      {url: `/api/attractions/route/get`, method: 'GET',
        params
    },
      options);
    }

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type UpdateRouteResult = NonNullable<Awaited<ReturnType<typeof updateRoute>>>
export type ListRoutesByPageResult = NonNullable<Awaited<ReturnType<typeof listRoutesByPage>>>
export type DeleteRouteResult = NonNullable<Awaited<ReturnType<typeof deleteRoute>>>
export type AddRouteResult = NonNullable<Awaited<ReturnType<typeof addRoute>>>
export type GetRouteByIdResult = NonNullable<Awaited<ReturnType<typeof getRouteById>>>
