/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  GetVideoByIdParams,
  IdRequest,
  PublicizeVideoAddRequest,
  PublicizeVideoQueryRequest,
  PublicizeVideoUpdateRequest,
  ResultBoolean,
  ResultPagePublicizeVideo,
  ResultPublicizeVideo,
  ResultString
} from '../../models';

import { mutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const updateVideo = (
    publicizeVideoUpdateRequest: PublicizeVideoUpdateRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/publicize/video/update`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: publicizeVideoUpdateRequest
    },
      options);
    }
  export const listVideosByPage = (
    publicizeVideoQueryRequest: PublicizeVideoQueryRequest,
 options?: SecondParameter<typeof mutator<ResultPagePublicizeVideo>>,) => {
      return mutator<ResultPagePublicizeVideo>(
      {url: `/api/publicize/video/list/page`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: publicizeVideoQueryRequest
    },
      options);
    }
  export const deleteVideo = (
    idRequest: IdRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/publicize/video/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: idRequest
    },
      options);
    }
  export const addVideo = (
    publicizeVideoAddRequest: PublicizeVideoAddRequest,
 options?: SecondParameter<typeof mutator<ResultString>>,) => {
      return mutator<ResultString>(
      {url: `/api/publicize/video/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: publicizeVideoAddRequest
    },
      options);
    }
  export const getVideoById = (
    params: GetVideoByIdParams,
 options?: SecondParameter<typeof mutator<ResultPublicizeVideo>>,) => {
      return mutator<ResultPublicizeVideo>(
      {url: `/api/publicize/video/get`, method: 'GET',
        params
    },
      options);
    }

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type UpdateVideoResult = NonNullable<Awaited<ReturnType<typeof updateVideo>>>
export type ListVideosByPageResult = NonNullable<Awaited<ReturnType<typeof listVideosByPage>>>
export type DeleteVideoResult = NonNullable<Awaited<ReturnType<typeof deleteVideo>>>
export type AddVideoResult = NonNullable<Awaited<ReturnType<typeof addVideo>>>
export type GetVideoByIdResult = NonNullable<Awaited<ReturnType<typeof getVideoById>>>
