/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  GetWeatherByIdParams,
  IdRequest,
  NaturalWeatherAddRequest,
  NaturalWeatherQueryRequest,
  NaturalWeatherUpdateRequest,
  ResultBoolean,
  ResultNaturalWeather,
  ResultPageNaturalWeather,
  ResultString
} from '../../models';

import { mutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const updateWeather = (
    naturalWeatherUpdateRequest: NaturalWeatherUpdateRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/natural/weather/update`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: naturalWeatherUpdateRequest
    },
      options);
    }
  export const listWeatherByPage = (
    naturalWeatherQueryRequest: NaturalWeatherQueryRequest,
 options?: SecondParameter<typeof mutator<ResultPageNaturalWeather>>,) => {
      return mutator<ResultPageNaturalWeather>(
      {url: `/api/natural/weather/list/page`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: naturalWeatherQueryRequest
    },
      options);
    }
  export const deleteWeather = (
    idRequest: IdRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/natural/weather/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: idRequest
    },
      options);
    }
  export const addWeather = (
    naturalWeatherAddRequest: NaturalWeatherAddRequest,
 options?: SecondParameter<typeof mutator<ResultString>>,) => {
      return mutator<ResultString>(
      {url: `/api/natural/weather/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: naturalWeatherAddRequest
    },
      options);
    }
  export const getWeatherById = (
    params: GetWeatherByIdParams,
 options?: SecondParameter<typeof mutator<ResultNaturalWeather>>,) => {
      return mutator<ResultNaturalWeather>(
      {url: `/api/natural/weather/get`, method: 'GET',
        params
    },
      options);
    }

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type UpdateWeatherResult = NonNullable<Awaited<ReturnType<typeof updateWeather>>>
export type ListWeatherByPageResult = NonNullable<Awaited<ReturnType<typeof listWeatherByPage>>>
export type DeleteWeatherResult = NonNullable<Awaited<ReturnType<typeof deleteWeather>>>
export type AddWeatherResult = NonNullable<Awaited<ReturnType<typeof addWeather>>>
export type GetWeatherByIdResult = NonNullable<Awaited<ReturnType<typeof getWeatherById>>>
