/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  GetTrackDetailParams,
  IdRequest,
  ResultBoolean,
  ResultPageTaskTrack,
  ResultString,
  ResultTaskTrackDetail,
  TaskTrackQueryRequest
} from '../../models';

import { mutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const startTrack = (

 options?: SecondParameter<typeof mutator<ResultString>>,) => {
      return mutator<ResultString>(
      {url: `/api/task/track/start`, method: 'POST'
    },
      options);
    }
  export const listTrackRecordsByPage = (
    taskTrackQueryRequest: TaskTrackQueryRequest,
 options?: SecondParameter<typeof mutator<ResultPageTaskTrack>>,) => {
      return mutator<ResultPageTaskTrack>(
      {url: `/api/task/track/list/page`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: taskTrackQueryRequest
    },
      options);
    }
  export const endTrack = (
    idRequest: IdRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/task/track/end`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: idRequest
    },
      options);
    }
  export const deleteTrack = (
    idRequest: IdRequest,
 options?: SecondParameter<typeof mutator<ResultBoolean>>,) => {
      return mutator<ResultBoolean>(
      {url: `/api/task/track/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: idRequest
    },
      options);
    }
  export const getTrackDetail = (
    params: GetTrackDetailParams,
 options?: SecondParameter<typeof mutator<ResultTaskTrackDetail>>,) => {
      return mutator<ResultTaskTrackDetail>(
      {url: `/api/task/track/get`, method: 'GET',
        params
    },
      options);
    }

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type StartTrackResult = NonNullable<Awaited<ReturnType<typeof startTrack>>>
export type ListTrackRecordsByPageResult = NonNullable<Awaited<ReturnType<typeof listTrackRecordsByPage>>>
export type EndTrackResult = NonNullable<Awaited<ReturnType<typeof endTrack>>>
export type DeleteTrackResult = NonNullable<Awaited<ReturnType<typeof deleteTrack>>>
export type GetTrackDetailResult = NonNullable<Awaited<ReturnType<typeof getTrackDetail>>>
