/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  ResultString,
  TaskTrackPointAddRequest
} from '../../models';

import { mutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const addPoint = (
    taskTrackPointAddRequest: TaskTrackPointAddRequest,
 options?: SecondParameter<typeof mutator<ResultString>>,) => {
      return mutator<ResultString>(
      {url: `/api/task/track/point/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: taskTrackPointAddRequest
    },
      options);
    }

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type AddPointResult = NonNullable<Awaited<ReturnType<typeof addPoint>>>
